# Form implementation generated from reading ui file '.\addonmanager.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddonManager(object):
    def setupUi(self, AddonManager):
        AddonManager.setObjectName("AddonManager")
        AddonManager.resize(800, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AddonManager.sizePolicy().hasHeightForWidth())
        AddonManager.setSizePolicy(sizePolicy)
        AddonManager.setMinimumSize(QtCore.QSize(800, 480))
        AddonManager.setMaximumSize(QtCore.QSize(800, 480))
        AddonManager.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        AddonManager.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=AddonManager)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 782, 384))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(-1, -1, 4, -1)
        self.gridLayout_2.setHorizontalSpacing(20)
        self.gridLayout_2.setVerticalSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 4, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_back = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_back.setMinimumSize(QtCore.QSize(0, 70))
        self.button_back.setMaximumSize(QtCore.QSize(5000, 100))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.button_back.setFont(font)
        self.button_back.setProperty("cssClass", "")
        self.button_back.setObjectName("button_back")
        self.horizontalLayout.addWidget(self.button_back)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        AddonManager.setCentralWidget(self.centralwidget)

        self.retranslateUi(AddonManager)
        QtCore.QMetaObject.connectSlotsByName(AddonManager)

    def retranslateUi(self, AddonManager):
        _translate = QtCore.QCoreApplication.translate
        AddonManager.setWindowTitle(_translate("AddonManager", "Addons Options"))
        self.button_back.setText(_translate("AddonManager", "< Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddonManager = QtWidgets.QMainWindow()
    ui = Ui_AddonManager()
    ui.setupUi(AddonManager)
    AddonManager.show()
    sys.exit(app.exec())
