# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addonwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Addonwindow(object):
    def setupUi(self, Addonwindow):
        Addonwindow.setObjectName("Addonwindow")
        Addonwindow.resize(800, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Addonwindow.sizePolicy().hasHeightForWidth())
        Addonwindow.setSizePolicy(sizePolicy)
        Addonwindow.setMinimumSize(QtCore.QSize(800, 480))
        Addonwindow.setMaximumSize(QtCore.QSize(800, 480))
        Addonwindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Addonwindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(Addonwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setLineWidth(1)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 782, 384))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.addon_container = QtWidgets.QVBoxLayout()
        self.addon_container.setObjectName("addon_container")
        self.gridLayout_2.addLayout(self.addon_container, 0, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 4, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_back = QtWidgets.QPushButton(self.centralwidget)
        self.button_back.setMinimumSize(QtCore.QSize(0, 70))
        self.button_back.setMaximumSize(QtCore.QSize(5000, 100))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.button_back.setFont(font)
        self.button_back.setObjectName("button_back")
        self.horizontalLayout.addWidget(self.button_back)
        self.selection_addon = QtWidgets.QComboBox(self.centralwidget)
        self.selection_addon.setMinimumSize(QtCore.QSize(105, 38))
        self.selection_addon.setMaximumSize(QtCore.QSize(5000, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.selection_addon.setFont(font)
        self.selection_addon.setMaxVisibleItems(11)
        self.selection_addon.setObjectName("selection_addon")
        self.horizontalLayout.addWidget(self.selection_addon)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        Addonwindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(Addonwindow)
        QtCore.QMetaObject.connectSlotsByName(Addonwindow)

    def retranslateUi(self, Addonwindow):
        _translate = QtCore.QCoreApplication.translate
        Addonwindow.setWindowTitle(_translate("Addonwindow", "Addons Options"))
        self.button_back.setText(_translate("Addonwindow", "< Back"))
        self.button_back.setProperty("cssClass", _translate("Addonwindow", "btn-inverted"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Addonwindow = QtWidgets.QMainWindow()
    ui = Ui_Addonwindow()
    ui.setupUi(Addonwindow)
    Addonwindow.show()
    sys.exit(app.exec_())
