# Form implementation generated from reading ui file '.\calibration.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CalibrationWindow(object):
    def setupUi(self, CalibrationWindow):
        CalibrationWindow.setObjectName("CalibrationWindow")
        CalibrationWindow.resize(800, 480)
        CalibrationWindow.setMinimumSize(QtCore.QSize(800, 480))
        CalibrationWindow.setMaximumSize(QtCore.QSize(800, 480))
        self.centralwidget = QtWidgets.QWidget(parent=CalibrationWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.stack = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stack.setObjectName("stack")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stack.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stack.addWidget(self.page_2)
        self.horizontalLayout_2.addWidget(self.stack)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_header = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_header.setMinimumSize(QtCore.QSize(0, 30))
        self.label_header.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_header.setFont(font)
        self.label_header.setStyleSheet("")
        self.label_header.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_header.setObjectName("label_header")
        self.horizontalLayout.addWidget(self.label_header)
        self.button_reset = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_reset.setMinimumSize(QtCore.QSize(100, 40))
        self.button_reset.setMaximumSize(QtCore.QSize(250, 150))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.button_reset.setFont(font)
        self.button_reset.setObjectName("button_reset")
        self.horizontalLayout.addWidget(self.button_reset)
        self.button_exit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_exit.setMinimumSize(QtCore.QSize(60, 50))
        self.button_exit.setMaximumSize(QtCore.QSize(60, 150))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.button_exit.setFont(font)
        self.button_exit.setObjectName("button_exit")
        self.horizontalLayout.addWidget(self.button_exit)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        self.verticalLayout_2.addLayout(self.gridLayout)
        CalibrationWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(CalibrationWindow)
        QtCore.QMetaObject.connectSlotsByName(CalibrationWindow)

    def retranslateUi(self, CalibrationWindow):
        _translate = QtCore.QCoreApplication.translate
        CalibrationWindow.setWindowTitle(_translate("CalibrationWindow", "Calibration"))
        self.label_header.setText(_translate("CalibrationWindow", "Pump Calibration Program"))
        self.label_header.setProperty("cssClass", _translate("CalibrationWindow", "bold secondary"))
        self.button_reset.setText(_translate("CalibrationWindow", "reset"))
        self.button_reset.setProperty("cssClass", _translate("CalibrationWindow", "neutral"))
        self.button_exit.setText(_translate("CalibrationWindow", "X"))
        self.button_exit.setProperty("cssClass", _translate("CalibrationWindow", "destructive btn-inverted"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CalibrationWindow = QtWidgets.QMainWindow()
    ui = Ui_CalibrationWindow()
    ui.setupUi(CalibrationWindow)
    CalibrationWindow.show()
    sys.exit(app.exec())
