# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\calibration_real.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CalibrationRealWidget(object):
    def setupUi(self, CalibrationRealWidget):
        CalibrationRealWidget.setObjectName("CalibrationRealWidget")
        CalibrationRealWidget.resize(804, 449)
        self.verticalLayout = QtWidgets.QVBoxLayout(CalibrationRealWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_measured = QtWidgets.QLabel(CalibrationRealWidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_measured.setFont(font)
        self.label_measured.setAlignment(QtCore.Qt.AlignCenter)
        self.label_measured.setObjectName("label_measured")
        self.gridLayout.addWidget(self.label_measured, 1, 2, 2, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.button_apply = QtWidgets.QPushButton(CalibrationRealWidget)
        self.button_apply.setMinimumSize(QtCore.QSize(0, 150))
        self.button_apply.setMaximumSize(QtCore.QSize(16777215, 500))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.button_apply.setFont(font)
        self.button_apply.setObjectName("button_apply")
        self.horizontalLayout_2.addWidget(self.button_apply)
        self.gridLayout.addLayout(self.horizontalLayout_2, 4, 0, 1, 3)
        self.label_new_flow = QtWidgets.QLabel(CalibrationRealWidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_new_flow.setFont(font)
        self.label_new_flow.setAlignment(QtCore.Qt.AlignCenter)
        self.label_new_flow.setObjectName("label_new_flow")
        self.gridLayout.addWidget(self.label_new_flow, 3, 0, 1, 3)
        self.input_measured_amount = ClickableLineEdit(CalibrationRealWidget)
        self.input_measured_amount.setMinimumSize(QtCore.QSize(0, 0))
        self.input_measured_amount.setMaximumSize(QtCore.QSize(16777215, 500))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.input_measured_amount.setFont(font)
        self.input_measured_amount.setAlignment(QtCore.Qt.AlignCenter)
        self.input_measured_amount.setObjectName("input_measured_amount")
        self.gridLayout.addWidget(self.input_measured_amount, 1, 1, 2, 1)
        self.label_spend_volume = QtWidgets.QLabel(CalibrationRealWidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_spend_volume.setFont(font)
        self.label_spend_volume.setAlignment(QtCore.Qt.AlignCenter)
        self.label_spend_volume.setObjectName("label_spend_volume")
        self.gridLayout.addWidget(self.label_spend_volume, 0, 1, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(CalibrationRealWidget)
        QtCore.QMetaObject.connectSlotsByName(CalibrationRealWidget)

    def retranslateUi(self, CalibrationRealWidget):
        _translate = QtCore.QCoreApplication.translate
        CalibrationRealWidget.setWindowTitle(_translate("CalibrationRealWidget", "Form"))
        self.label_measured.setText(_translate("CalibrationRealWidget", "<html><head/><body><p>ml Measured</p></body></html>"))
        self.label_measured.setProperty("cssClass", _translate("CalibrationRealWidget", "bold"))
        self.button_apply.setText(_translate("CalibrationRealWidget", "Apply"))
        self.button_apply.setProperty("cssClass", _translate("CalibrationRealWidget", "btn-inverted"))
        self.label_new_flow.setText(_translate("CalibrationRealWidget", "New Volume Flow: XX ml/s"))
        self.label_new_flow.setProperty("cssClass", _translate("CalibrationRealWidget", "bold"))
        self.input_measured_amount.setProperty("cssClass", _translate("CalibrationRealWidget", "secondary bold"))
        self.label_spend_volume.setText(_translate("CalibrationRealWidget", "Spend: XX ml"))
        self.label_spend_volume.setProperty("cssClass", _translate("CalibrationRealWidget", "bold"))
from src.ui_elements.clickablelineedit import ClickableLineEdit


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CalibrationRealWidget = QtWidgets.QWidget()
    ui = Ui_CalibrationRealWidget()
    ui.setupUi(CalibrationRealWidget)
    CalibrationRealWidget.show()
    sys.exit(app.exec_())
