# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\customprompt.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CustomPrompt(object):
    def setupUi(self, CustomPrompt):
        CustomPrompt.setObjectName("CustomPrompt")
        CustomPrompt.resize(800, 480)
        CustomPrompt.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(CustomPrompt)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(CustomPrompt)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setLineWidth(1)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 782, 354))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setContentsMargins(0, 0, 4, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.information = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.information.setMinimumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.information.setFont(font)
        self.information.setAlignment(QtCore.Qt.AlignCenter)
        self.information.setWordWrap(True)
        self.information.setObjectName("information")
        self.verticalLayout_3.addWidget(self.information)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.no_button = QtWidgets.QPushButton(CustomPrompt)
        self.no_button.setMinimumSize(QtCore.QSize(0, 100))
        self.no_button.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.no_button.setFont(font)
        self.no_button.setProperty("cssClass", "")
        self.no_button.setObjectName("no_button")
        self.horizontalLayout.addWidget(self.no_button)
        self.yes_button = QtWidgets.QPushButton(CustomPrompt)
        self.yes_button.setMinimumSize(QtCore.QSize(0, 100))
        self.yes_button.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.yes_button.setFont(font)
        self.yes_button.setObjectName("yes_button")
        self.horizontalLayout.addWidget(self.yes_button)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(CustomPrompt)
        QtCore.QMetaObject.connectSlotsByName(CustomPrompt)

    def retranslateUi(self, CustomPrompt):
        _translate = QtCore.QCoreApplication.translate
        CustomPrompt.setWindowTitle(_translate("CustomPrompt", "Question"))
        self.information.setText(_translate("CustomPrompt", "Message Label which is really damn long"))
        self.no_button.setText(_translate("CustomPrompt", "No"))
        self.yes_button.setText(_translate("CustomPrompt", "Yes"))
        self.yes_button.setProperty("cssClass", _translate("CustomPrompt", "btn-inverted"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CustomPrompt = QtWidgets.QDialog()
    ui = Ui_CustomPrompt()
    ui.setupUi(CustomPrompt)
    CustomPrompt.show()
    sys.exit(app.exec_())
