# Form implementation generated from reading ui file 'customdialog.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CustomDialog(object):
    def setupUi(self, CustomDialog):
        CustomDialog.setObjectName("CustomDialog")
        CustomDialog.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        CustomDialog.resize(800, 480)
        CustomDialog.setMinimumSize(QtCore.QSize(800, 480))
        CustomDialog.setMaximumSize(QtCore.QSize(800, 480))
        self.centralwidget = QtWidgets.QWidget(parent=CustomDialog)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.informationLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.informationLabel.setMinimumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.informationLabel.setFont(font)
        self.informationLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.informationLabel.setWordWrap(True)
        self.informationLabel.setObjectName("informationLabel")
        self.verticalLayout_2.addWidget(self.informationLabel)
        self.closeButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.closeButton.setMinimumSize(QtCore.QSize(0, 50))
        self.closeButton.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.closeButton.setFont(font)
        self.closeButton.setObjectName("closeButton")
        self.verticalLayout_2.addWidget(self.closeButton)
        CustomDialog.setCentralWidget(self.centralwidget)

        self.retranslateUi(CustomDialog)
        QtCore.QMetaObject.connectSlotsByName(CustomDialog)

    def retranslateUi(self, CustomDialog):
        _translate = QtCore.QCoreApplication.translate
        CustomDialog.setWindowTitle(_translate("CustomDialog", "Information"))
        self.informationLabel.setText(_translate("CustomDialog", "Message Label which is really damn long"))
        self.closeButton.setText(_translate("CustomDialog", "Close"))
        self.closeButton.setProperty("cssClass", _translate("CustomDialog", "btn-inverted"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CustomDialog = QtWidgets.QMainWindow()
    ui = Ui_CustomDialog()
    ui.setupUi(CustomDialog)
    CustomDialog.show()
    sys.exit(app.exec())
