# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\datawindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DataWindow(object):
    def setupUi(self, DataWindow):
        DataWindow.setObjectName("DataWindow")
        DataWindow.resize(800, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DataWindow.sizePolicy().hasHeightForWidth())
        DataWindow.setSizePolicy(sizePolicy)
        DataWindow.setMinimumSize(QtCore.QSize(800, 480))
        DataWindow.setMaximumSize(QtCore.QSize(800, 480))
        DataWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        DataWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(DataWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_back = QtWidgets.QPushButton(self.centralwidget)
        self.button_back.setMaximumSize(QtCore.QSize(5000, 300))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.button_back.setFont(font)
        self.button_back.setObjectName("button_back")
        self.horizontalLayout.addWidget(self.button_back)
        self.button_reset = QtWidgets.QPushButton(self.centralwidget)
        self.button_reset.setMaximumSize(QtCore.QSize(5000, 300))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.button_reset.setFont(font)
        self.button_reset.setObjectName("button_reset")
        self.horizontalLayout.addWidget(self.button_reset)
        self.selection_data = QtWidgets.QComboBox(self.centralwidget)
        self.selection_data.setMinimumSize(QtCore.QSize(105, 38))
        self.selection_data.setMaximumSize(QtCore.QSize(5000, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.selection_data.setFont(font)
        self.selection_data.setMaxVisibleItems(11)
        self.selection_data.setObjectName("selection_data")
        self.horizontalLayout.addWidget(self.selection_data)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setLineWidth(1)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 782, 401))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.content_container = QtWidgets.QVBoxLayout()
        self.content_container.setObjectName("content_container")
        self.label_made_cocktails = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_made_cocktails.setMaximumSize(QtCore.QSize(900, 80))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_made_cocktails.setFont(font)
        self.label_made_cocktails.setAlignment(QtCore.Qt.AlignCenter)
        self.label_made_cocktails.setObjectName("label_made_cocktails")
        self.content_container.addWidget(self.label_made_cocktails)
        self.verticalLayout_3.addLayout(self.content_container)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        DataWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(DataWindow)
        QtCore.QMetaObject.connectSlotsByName(DataWindow)

    def retranslateUi(self, DataWindow):
        _translate = QtCore.QCoreApplication.translate
        DataWindow.setWindowTitle(_translate("DataWindow", "Data"))
        self.button_back.setText(_translate("DataWindow", "< Back"))
        self.button_back.setProperty("cssClass", _translate("DataWindow", "btn-inverted"))
        self.button_reset.setText(_translate("DataWindow", "Reset"))
        self.button_reset.setProperty("cssClass", _translate("DataWindow", "btn-inverted"))
        self.label_made_cocktails.setText(_translate("DataWindow", "Cocktail(s) made: XX"))
        self.label_made_cocktails.setProperty("cssClass", _translate("DataWindow", "header-underline bold"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DataWindow = QtWidgets.QMainWindow()
    ui = Ui_DataWindow()
    ui.setupUi(DataWindow)
    DataWindow.show()
    sys.exit(app.exec_())
