# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\datepicker.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_datepicker(object):
    def setupUi(self, datepicker):
        datepicker.setObjectName("datepicker")
        datepicker.resize(800, 480)
        datepicker.setMinimumSize(QtCore.QSize(800, 480))
        datepicker.setMaximumSize(QtCore.QSize(800, 480))
        self.centralwidget = QtWidgets.QWidget(datepicker)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.header = QtWidgets.QLabel(self.centralwidget)
        self.header.setMinimumSize(QtCore.QSize(0, 100))
        self.header.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.header.setFont(font)
        self.header.setAlignment(QtCore.Qt.AlignCenter)
        self.header.setObjectName("header")
        self.verticalLayout_2.addWidget(self.header)
        self.selected_date = QtWidgets.QDateEdit(self.centralwidget)
        self.selected_date.setMinimumSize(QtCore.QSize(0, 50))
        self.selected_date.setMaximumSize(QtCore.QSize(16777215, 200))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.selected_date.setFont(font)
        self.selected_date.setCalendarPopup(False)
        self.selected_date.setObjectName("selected_date")
        self.verticalLayout_2.addWidget(self.selected_date)
        self.selected_time = QtWidgets.QTimeEdit(self.centralwidget)
        self.selected_time.setMinimumSize(QtCore.QSize(0, 50))
        self.selected_time.setMaximumSize(QtCore.QSize(16777215, 200))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.selected_time.setFont(font)
        self.selected_time.setCalendarPopup(False)
        self.selected_time.setObjectName("selected_time")
        self.verticalLayout_2.addWidget(self.selected_time)
        self.pb_ok = QtWidgets.QPushButton(self.centralwidget)
        self.pb_ok.setMinimumSize(QtCore.QSize(0, 70))
        self.pb_ok.setMaximumSize(QtCore.QSize(16777215, 200))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.pb_ok.setFont(font)
        self.pb_ok.setObjectName("pb_ok")
        self.verticalLayout_2.addWidget(self.pb_ok)
        datepicker.setCentralWidget(self.centralwidget)

        self.retranslateUi(datepicker)
        QtCore.QMetaObject.connectSlotsByName(datepicker)

    def retranslateUi(self, datepicker):
        _translate = QtCore.QCoreApplication.translate
        datepicker.setWindowTitle(_translate("datepicker", "datepicker"))
        self.header.setText(_translate("datepicker", "Select Date and Time"))
        self.header.setProperty("cssClass", _translate("datepicker", "neutral bold"))
        self.selected_date.setProperty("cssClass", _translate("datepicker", "bold"))
        self.selected_time.setProperty("cssClass", _translate("datepicker", "bold"))
        self.pb_ok.setText(_translate("datepicker", "Ok"))
        self.pb_ok.setProperty("cssClass", _translate("datepicker", "btn-inverted"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    datepicker = QtWidgets.QMainWindow()
    ui = Ui_datepicker()
    ui.setupUi(datepicker)
    datepicker.show()
    sys.exit(app.exec_())
