# Form implementation generated from reading ui file 'event_window.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EventWindow(object):
    def setupUi(self, EventWindow):
        EventWindow.setObjectName("EventWindow")
        EventWindow.resize(800, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(EventWindow.sizePolicy().hasHeightForWidth())
        EventWindow.setSizePolicy(sizePolicy)
        EventWindow.setMinimumSize(QtCore.QSize(800, 480))
        EventWindow.setMaximumSize(QtCore.QSize(800, 480))
        EventWindow.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        EventWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=EventWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_back = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_back.setMaximumSize(QtCore.QSize(5000, 300))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        self.button_back.setFont(font)
        self.button_back.setObjectName("button_back")
        self.horizontalLayout.addWidget(self.button_back)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.selection_event = QtWidgets.QComboBox(parent=self.centralwidget)
        self.selection_event.setMinimumSize(QtCore.QSize(105, 38))
        self.selection_event.setMaximumSize(QtCore.QSize(5000, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.selection_event.setFont(font)
        self.selection_event.setMaxVisibleItems(11)
        self.selection_event.setObjectName("selection_event")
        self.horizontalLayout.addWidget(self.selection_event)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.text_display = QtWidgets.QTextBrowser(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.text_display.setFont(font)
        self.text_display.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.text_display.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.text_display.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.text_display.setLineWrapMode(QtWidgets.QTextEdit.LineWrapMode.NoWrap)
        self.text_display.setObjectName("text_display")
        self.verticalLayout_2.addWidget(self.text_display)
        EventWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(EventWindow)
        QtCore.QMetaObject.connectSlotsByName(EventWindow)

    def retranslateUi(self, EventWindow):
        _translate = QtCore.QCoreApplication.translate
        EventWindow.setWindowTitle(_translate("EventWindow", "Logs"))
        self.button_back.setText(_translate("EventWindow", "< Back"))
        self.button_back.setProperty("cssClass", _translate("EventWindow", "btn-inverted"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EventWindow = QtWidgets.QMainWindow()
    ui = Ui_EventWindow()
    ui.setupUi(EventWindow)
    EventWindow.show()
    sys.exit(app.exec())
