# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\logwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LogWindow(object):
    def setupUi(self, LogWindow):
        LogWindow.setObjectName("LogWindow")
        LogWindow.resize(800, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LogWindow.sizePolicy().hasHeightForWidth())
        LogWindow.setSizePolicy(sizePolicy)
        LogWindow.setMinimumSize(QtCore.QSize(800, 480))
        LogWindow.setMaximumSize(QtCore.QSize(800, 480))
        LogWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        LogWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(LogWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_back = QtWidgets.QPushButton(self.centralwidget)
        self.button_back.setMaximumSize(QtCore.QSize(5000, 300))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.button_back.setFont(font)
        self.button_back.setObjectName("button_back")
        self.horizontalLayout.addWidget(self.button_back)
        self.check_warning = QtWidgets.QCheckBox(self.centralwidget)
        self.check_warning.setMaximumSize(QtCore.QSize(160, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.check_warning.setFont(font)
        self.check_warning.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.check_warning.setIconSize(QtCore.QSize(50, 50))
        self.check_warning.setTristate(False)
        self.check_warning.setObjectName("check_warning")
        self.horizontalLayout.addWidget(self.check_warning)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.selection_logs = QtWidgets.QComboBox(self.centralwidget)
        self.selection_logs.setMinimumSize(QtCore.QSize(105, 38))
        self.selection_logs.setMaximumSize(QtCore.QSize(5000, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.selection_logs.setFont(font)
        self.selection_logs.setMaxVisibleItems(11)
        self.selection_logs.setObjectName("selection_logs")
        self.horizontalLayout.addWidget(self.selection_logs)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.text_display = QtWidgets.QTextBrowser(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.text_display.setFont(font)
        self.text_display.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.text_display.setFrameShadow(QtWidgets.QFrame.Plain)
        self.text_display.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.text_display.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.text_display.setObjectName("text_display")
        self.verticalLayout_2.addWidget(self.text_display)
        LogWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LogWindow)
        QtCore.QMetaObject.connectSlotsByName(LogWindow)

    def retranslateUi(self, LogWindow):
        _translate = QtCore.QCoreApplication.translate
        LogWindow.setWindowTitle(_translate("LogWindow", "Logs"))
        self.button_back.setText(_translate("LogWindow", "< Back"))
        self.button_back.setProperty("cssClass", _translate("LogWindow", "btn-inverted"))
        self.check_warning.setText(_translate("LogWindow", "WARNING +"))
        self.check_warning.setProperty("cssClass", _translate("LogWindow", "bold center"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LogWindow = QtWidgets.QMainWindow()
    ui = Ui_LogWindow()
    ui.setupUi(LogWindow)
    LogWindow.show()
    sys.exit(app.exec_())
