# Form implementation generated from reading ui file '.\news_window.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_NewsWindow(object):
    def setupUi(self, NewsWindow):
        NewsWindow.setObjectName("NewsWindow")
        NewsWindow.resize(800, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(NewsWindow.sizePolicy().hasHeightForWidth())
        NewsWindow.setSizePolicy(sizePolicy)
        NewsWindow.setMinimumSize(QtCore.QSize(800, 480))
        NewsWindow.setMaximumSize(QtCore.QSize(800, 480))
        NewsWindow.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        NewsWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=NewsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_back = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_back.setMaximumSize(QtCore.QSize(5000, 300))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        self.button_back.setFont(font)
        self.button_back.setObjectName("button_back")
        self.horizontalLayout.addWidget(self.button_back)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.scroll_area = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scroll_area.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.scroll_area.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.scroll_area.setLineWidth(1)
        self.scroll_area.setWidgetResizable(True)
        self.scroll_area.setObjectName("scroll_area")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 782, 397))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.data_container = QtWidgets.QVBoxLayout()
        self.data_container.setContentsMargins(9, 3, 6, 15)
        self.data_container.setSpacing(6)
        self.data_container.setObjectName("data_container")
        self.verticalLayout_5.addLayout(self.data_container)
        self.scroll_area.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.addWidget(self.scroll_area)
        NewsWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(NewsWindow)
        QtCore.QMetaObject.connectSlotsByName(NewsWindow)

    def retranslateUi(self, NewsWindow):
        _translate = QtCore.QCoreApplication.translate
        NewsWindow.setWindowTitle(_translate("NewsWindow", "News"))
        self.button_back.setText(_translate("NewsWindow", "< Back"))
        self.button_back.setProperty("cssClass", _translate("NewsWindow", "btn-inverted"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NewsWindow = QtWidgets.QMainWindow()
    ui = Ui_NewsWindow()
    ui.setupUi(NewsWindow)
    NewsWindow.show()
    sys.exit(app.exec())
