# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\optionwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Optionwindow(object):
    def setupUi(self, Optionwindow):
        Optionwindow.setObjectName("Optionwindow")
        Optionwindow.resize(800, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Optionwindow.sizePolicy().hasHeightForWidth())
        Optionwindow.setSizePolicy(sizePolicy)
        Optionwindow.setMinimumSize(QtCore.QSize(800, 480))
        Optionwindow.setMaximumSize(QtCore.QSize(800, 480))
        Optionwindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Optionwindow.setStyleSheet("QWidget\n"
"{\n"
"    color: rgb(0, 123, 255);    \n"
"    background-color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: (0, 123, 255);\n"
"    border-width: 4px;\n"
"    border-color: rgb(0, 123, 255);\n"
"    border-style: solid;\n"
"    border-radius: 7;\n"
"    padding: 3px;\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    color: rgb(239, 151, 0);    \n"
"    border-color: rgb(239, 151, 0);\n"
"}\n"
"\n"
"QProgressBar\n"
"{\n"
"    background-color: rgb(166, 166, 166);\n"
"    color: rgb(0, 0, 0);\n"
"    border: 2px rgb(166, 166, 166);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    border: 2px rgb(166, 166, 166);\n"
"    border-top-left-radius: 5px;\n"
"    border-bottom-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    border-bottom-right-radius: 5px;\n"
"    background-color: rgb(0, 123, 255);\n"
"   /* width: 40px;\n"
"    margin: 0.5px;*/\n"
"}\n"
"\n"
"#Labbruch {\n"
"    color: rgb(239, 151, 0);\n"
"}\n"
"\n"
"#LProgress{\n"
"    color: rgb(239, 151, 0);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(Optionwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.button_config = QtWidgets.QPushButton(self.centralwidget)
        self.button_config.setMaximumSize(QtCore.QSize(5000, 300))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.button_config.setFont(font)
        self.button_config.setObjectName("button_config")
        self.gridLayout.addWidget(self.button_config, 2, 0, 1, 1)
        self.button_back = QtWidgets.QPushButton(self.centralwidget)
        self.button_back.setMaximumSize(QtCore.QSize(5000, 300))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.button_back.setFont(font)
        self.button_back.setObjectName("button_back")
        self.gridLayout.addWidget(self.button_back, 3, 0, 1, 1)
        self.button_clean = QtWidgets.QPushButton(self.centralwidget)
        self.button_clean.setMaximumSize(QtCore.QSize(5000, 300))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.button_clean.setFont(font)
        self.button_clean.setObjectName("button_clean")
        self.gridLayout.addWidget(self.button_clean, 1, 0, 1, 1)
        Optionwindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(Optionwindow)
        QtCore.QMetaObject.connectSlotsByName(Optionwindow)

    def retranslateUi(self, Optionwindow):
        _translate = QtCore.QCoreApplication.translate
        Optionwindow.setWindowTitle(_translate("Optionwindow", "Options"))
        self.button_config.setText(_translate("Optionwindow", "Change Config"))
        self.button_back.setText(_translate("Optionwindow", "< Back"))
        self.button_clean.setText(_translate("Optionwindow", "Clean Machine"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Optionwindow = QtWidgets.QMainWindow()
    ui = Ui_Optionwindow()
    ui.setupUi(Optionwindow)
    Optionwindow.show()
    sys.exit(app.exec_())
