# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\refill_prompt.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RefillPrompt(object):
    def setupUi(self, RefillPrompt):
        RefillPrompt.setObjectName("RefillPrompt")
        RefillPrompt.resize(800, 480)
        RefillPrompt.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(RefillPrompt)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_message = QtWidgets.QLabel(RefillPrompt)
        self.label_message.setMinimumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_message.setFont(font)
        self.label_message.setAlignment(QtCore.Qt.AlignCenter)
        self.label_message.setWordWrap(True)
        self.label_message.setObjectName("label_message")
        self.verticalLayout.addWidget(self.label_message)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.virgin_checkbox = QtWidgets.QCheckBox(RefillPrompt)
        self.virgin_checkbox.setEnabled(True)
        self.virgin_checkbox.setMaximumSize(QtCore.QSize(300, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.virgin_checkbox.setFont(font)
        self.virgin_checkbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.virgin_checkbox.setIconSize(QtCore.QSize(50, 50))
        self.virgin_checkbox.setTristate(False)
        self.virgin_checkbox.setObjectName("virgin_checkbox")
        self.horizontalLayout_2.addWidget(self.virgin_checkbox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.button_apply = QtWidgets.QPushButton(RefillPrompt)
        self.button_apply.setEnabled(False)
        self.button_apply.setMinimumSize(QtCore.QSize(0, 50))
        self.button_apply.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.button_apply.setFont(font)
        self.button_apply.setObjectName("button_apply")
        self.verticalLayout.addWidget(self.button_apply)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_later = QtWidgets.QPushButton(RefillPrompt)
        self.button_later.setMinimumSize(QtCore.QSize(0, 50))
        self.button_later.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.button_later.setFont(font)
        self.button_later.setProperty("cssClass", "")
        self.button_later.setObjectName("button_later")
        self.horizontalLayout.addWidget(self.button_later)
        self.button_to_bottles = QtWidgets.QPushButton(RefillPrompt)
        self.button_to_bottles.setMinimumSize(QtCore.QSize(0, 50))
        self.button_to_bottles.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.button_to_bottles.setFont(font)
        self.button_to_bottles.setObjectName("button_to_bottles")
        self.horizontalLayout.addWidget(self.button_to_bottles)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(RefillPrompt)
        QtCore.QMetaObject.connectSlotsByName(RefillPrompt)

    def retranslateUi(self, RefillPrompt):
        _translate = QtCore.QCoreApplication.translate
        RefillPrompt.setWindowTitle(_translate("RefillPrompt", "Not enough Ingredient"))
        self.label_message.setText(_translate("RefillPrompt", "Message Label which is really damn long"))
        self.virgin_checkbox.setText(_translate("RefillPrompt", "Done!"))
        self.virgin_checkbox.setProperty("cssClass", _translate("RefillPrompt", "bold"))
        self.button_apply.setText(_translate("RefillPrompt", "Apply"))
        self.button_apply.setProperty("cssClass", _translate("RefillPrompt", "btn-inverted"))
        self.button_later.setText(_translate("RefillPrompt", "< Later"))
        self.button_to_bottles.setText(_translate("RefillPrompt", "Go to Bottles"))
        self.button_to_bottles.setProperty("cssClass", _translate("RefillPrompt", "btn-inverted"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RefillPrompt = QtWidgets.QDialog()
    ui = Ui_RefillPrompt()
    ui.setupUi(RefillPrompt)
    RefillPrompt.show()
    sys.exit(app.exec_())
