# Form implementation generated from reading ui file '.\resource_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ResourceWindow(object):
    def setupUi(self, ResourceWindow):
        ResourceWindow.setObjectName("ResourceWindow")
        ResourceWindow.resize(800, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ResourceWindow.sizePolicy().hasHeightForWidth())
        ResourceWindow.setSizePolicy(sizePolicy)
        ResourceWindow.setMinimumSize(QtCore.QSize(800, 480))
        ResourceWindow.setMaximumSize(QtCore.QSize(800, 480))
        ResourceWindow.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        ResourceWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=ResourceWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_back = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_back.setMaximumSize(QtCore.QSize(5000, 300))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.button_back.setFont(font)
        self.button_back.setObjectName("button_back")
        self.horizontalLayout.addWidget(self.button_back)
        self.selection_data = QtWidgets.QComboBox(parent=self.centralwidget)
        self.selection_data.setMinimumSize(QtCore.QSize(105, 38))
        self.selection_data.setMaximumSize(QtCore.QSize(5000, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.selection_data.setFont(font)
        self.selection_data.setMaxVisibleItems(11)
        self.selection_data.setObjectName("selection_data")
        self.horizontalLayout.addWidget(self.selection_data)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.scrollArea.setLineWidth(1)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 782, 390))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.content_container = QtWidgets.QVBoxLayout()
        self.content_container.setContentsMargins(-1, -1, 5, -1)
        self.content_container.setObjectName("content_container")
        self.verticalLayout_3.addLayout(self.content_container)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        ResourceWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ResourceWindow)
        QtCore.QMetaObject.connectSlotsByName(ResourceWindow)

    def retranslateUi(self, ResourceWindow):
        _translate = QtCore.QCoreApplication.translate
        ResourceWindow.setWindowTitle(_translate("ResourceWindow", "Data"))
        self.button_back.setText(_translate("ResourceWindow", "< Back"))
        self.button_back.setProperty("cssClass", _translate("ResourceWindow", "btn-inverted"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ResourceWindow = QtWidgets.QMainWindow()
    ui = Ui_ResourceWindow()
    ui.setupUi(ResourceWindow)
    ResourceWindow.show()
    sys.exit(app.exec())
