# Form implementation generated from reading ui file 'rfidwriter.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RFIDWriterWindow(object):
    def setupUi(self, RFIDWriterWindow):
        RFIDWriterWindow.setObjectName("RFIDWriterWindow")
        RFIDWriterWindow.resize(800, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(RFIDWriterWindow.sizePolicy().hasHeightForWidth())
        RFIDWriterWindow.setSizePolicy(sizePolicy)
        RFIDWriterWindow.setMinimumSize(QtCore.QSize(800, 480))
        RFIDWriterWindow.setMaximumSize(QtCore.QSize(800, 480))
        RFIDWriterWindow.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        RFIDWriterWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=RFIDWriterWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.button_back = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_back.setMaximumSize(QtCore.QSize(5000, 300))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.button_back.setFont(font)
        self.button_back.setObjectName("button_back")
        self.gridLayout.addWidget(self.button_back, 2, 0, 1, 1)
        self.button_write = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_write.setMaximumSize(QtCore.QSize(5000, 300))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.button_write.setFont(font)
        self.button_write.setObjectName("button_write")
        self.gridLayout.addWidget(self.button_write, 2, 1, 1, 1)
        self.label_information = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_information.setMaximumSize(QtCore.QSize(16777215, 600))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label_information.setFont(font)
        self.label_information.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_information.setObjectName("label_information")
        self.gridLayout.addWidget(self.label_information, 1, 0, 1, 2)
        self.input_text = ClickableLineEdit(parent=self.centralwidget)
        self.input_text.setMinimumSize(QtCore.QSize(0, 50))
        self.input_text.setMaximumSize(QtCore.QSize(16777215, 120))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.input_text.setFont(font)
        self.input_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.input_text.setObjectName("input_text")
        self.gridLayout.addWidget(self.input_text, 0, 0, 1, 2)
        RFIDWriterWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(RFIDWriterWindow)
        QtCore.QMetaObject.connectSlotsByName(RFIDWriterWindow)

    def retranslateUi(self, RFIDWriterWindow):
        _translate = QtCore.QCoreApplication.translate
        RFIDWriterWindow.setWindowTitle(_translate("RFIDWriterWindow", "Write RFID"))
        self.button_back.setText(_translate("RFIDWriterWindow", "< Back"))
        self.button_write.setText(_translate("RFIDWriterWindow", "Write"))
        self.button_write.setProperty("cssClass", _translate("RFIDWriterWindow", "btn-inverted"))
        self.label_information.setText(_translate("RFIDWriterWindow", "Information"))
        self.label_information.setProperty("cssClass", _translate("RFIDWriterWindow", "secondary bold"))
        self.input_text.setProperty("cssClass", _translate("RFIDWriterWindow", "bold"))
from src.ui_elements.clickablelineedit import ClickableLineEdit


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RFIDWriterWindow = QtWidgets.QMainWindow()
    ui = Ui_RFIDWriterWindow()
    ui.setupUi(RFIDWriterWindow)
    RFIDWriterWindow.show()
    sys.exit(app.exec())
