# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\rfidwriter.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RFIDWindow(object):
    def setupUi(self, RFIDWindow):
        RFIDWindow.setObjectName("RFIDWindow")
        RFIDWindow.resize(800, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(RFIDWindow.sizePolicy().hasHeightForWidth())
        RFIDWindow.setSizePolicy(sizePolicy)
        RFIDWindow.setMinimumSize(QtCore.QSize(800, 480))
        RFIDWindow.setMaximumSize(QtCore.QSize(800, 480))
        RFIDWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        RFIDWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(RFIDWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.button_back = QtWidgets.QPushButton(self.centralwidget)
        self.button_back.setMaximumSize(QtCore.QSize(5000, 300))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.button_back.setFont(font)
        self.button_back.setObjectName("button_back")
        self.gridLayout.addWidget(self.button_back, 2, 0, 1, 1)
        self.button_write = QtWidgets.QPushButton(self.centralwidget)
        self.button_write.setMaximumSize(QtCore.QSize(5000, 300))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.button_write.setFont(font)
        self.button_write.setObjectName("button_write")
        self.gridLayout.addWidget(self.button_write, 2, 1, 1, 1)
        self.label_information = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label_information.setFont(font)
        self.label_information.setAlignment(QtCore.Qt.AlignCenter)
        self.label_information.setObjectName("label_information")
        self.gridLayout.addWidget(self.label_information, 1, 0, 1, 2)
        self.input_text = QtWidgets.QLineEdit(self.centralwidget)
        self.input_text.setMinimumSize(QtCore.QSize(0, 50))
        self.input_text.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.input_text.setFont(font)
        self.input_text.setObjectName("input_text")
        self.gridLayout.addWidget(self.input_text, 0, 0, 1, 2)
        RFIDWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(RFIDWindow)
        QtCore.QMetaObject.connectSlotsByName(RFIDWindow)

    def retranslateUi(self, RFIDWindow):
        _translate = QtCore.QCoreApplication.translate
        RFIDWindow.setWindowTitle(_translate("RFIDWindow", "Write RFID"))
        self.button_back.setText(_translate("RFIDWindow", "< Back"))
        self.button_write.setText(_translate("RFIDWindow", "Write"))
        self.button_write.setProperty("cssClass", _translate("RFIDWindow", "btn-inverted"))
        self.label_information.setText(_translate("RFIDWindow", "Information"))
        self.label_information.setProperty("cssClass", _translate("RFIDWindow", "secondary bold"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RFIDWindow = QtWidgets.QMainWindow()
    ui = Ui_RFIDWindow()
    ui.setupUi(RFIDWindow)
    RFIDWindow.show()
    sys.exit(app.exec_())
