# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\searchwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SearchWindow(object):
    def setupUi(self, SearchWindow):
        SearchWindow.setObjectName("SearchWindow")
        SearchWindow.resize(800, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SearchWindow.sizePolicy().hasHeightForWidth())
        SearchWindow.setSizePolicy(sizePolicy)
        SearchWindow.setMinimumSize(QtCore.QSize(800, 480))
        SearchWindow.setMaximumSize(QtCore.QSize(800, 480))
        SearchWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        SearchWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(SearchWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.button_back = QtWidgets.QPushButton(self.centralwidget)
        self.button_back.setMinimumSize(QtCore.QSize(0, 80))
        self.button_back.setMaximumSize(QtCore.QSize(5000, 80))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.button_back.setFont(font)
        self.button_back.setObjectName("button_back")
        self.gridLayout.addWidget(self.button_back, 4, 0, 1, 1)
        self.button_enter = QtWidgets.QPushButton(self.centralwidget)
        self.button_enter.setMinimumSize(QtCore.QSize(0, 80))
        self.button_enter.setMaximumSize(QtCore.QSize(5000, 80))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.button_enter.setFont(font)
        self.button_enter.setObjectName("button_enter")
        self.gridLayout.addWidget(self.button_enter, 4, 1, 1, 1)
        self.input_cocktail = ClickableLineEdit(self.centralwidget)
        self.input_cocktail.setMinimumSize(QtCore.QSize(0, 50))
        self.input_cocktail.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.input_cocktail.setFont(font)
        self.input_cocktail.setAlignment(QtCore.Qt.AlignCenter)
        self.input_cocktail.setObjectName("input_cocktail")
        self.gridLayout.addWidget(self.input_cocktail, 1, 0, 1, 2)
        self.label_titel = QtWidgets.QLabel(self.centralwidget)
        self.label_titel.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_titel.setFont(font)
        self.label_titel.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titel.setObjectName("label_titel")
        self.gridLayout.addWidget(self.label_titel, 0, 0, 1, 2)
        self.list_widget_cocktails = QtWidgets.QListWidget(self.centralwidget)
        self.list_widget_cocktails.setMaximumSize(QtCore.QSize(5000, 5000))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.list_widget_cocktails.setFont(font)
        self.list_widget_cocktails.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_widget_cocktails.setTextElideMode(QtCore.Qt.ElideRight)
        self.list_widget_cocktails.setObjectName("list_widget_cocktails")
        self.gridLayout.addWidget(self.list_widget_cocktails, 2, 0, 1, 2)
        SearchWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(SearchWindow)
        QtCore.QMetaObject.connectSlotsByName(SearchWindow)

    def retranslateUi(self, SearchWindow):
        _translate = QtCore.QCoreApplication.translate
        SearchWindow.setWindowTitle(_translate("SearchWindow", "Search Available Cocktails"))
        self.button_back.setText(_translate("SearchWindow", "< Back"))
        self.button_enter.setText(_translate("SearchWindow", "Enter"))
        self.button_enter.setProperty("cssClass", _translate("SearchWindow", "btn-inverted"))
        self.input_cocktail.setProperty("cssClass", _translate("SearchWindow", "bold"))
        self.label_titel.setText(_translate("SearchWindow", "Search available cocktails by name or ingredient"))
        self.label_titel.setProperty("cssClass", _translate("SearchWindow", "secondary bold"))
        self.list_widget_cocktails.setSortingEnabled(True)
from src.ui_elements.clickablelineedit import ClickableLineEdit


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SearchWindow = QtWidgets.QMainWindow()
    ui = Ui_SearchWindow()
    ui.setupUi(SearchWindow)
    SearchWindow.show()
    sys.exit(app.exec_())
