# Form implementation generated from reading ui file '.\teamselection.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Teamselection(object):
    def setupUi(self, Teamselection):
        Teamselection.setObjectName("Teamselection")
        Teamselection.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        Teamselection.resize(800, 480)
        Teamselection.setMinimumSize(QtCore.QSize(800, 480))
        Teamselection.setMaximumSize(QtCore.QSize(800, 480))
        self.centralwidget = QtWidgets.QWidget(parent=Teamselection)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.LHeader = QtWidgets.QLabel(parent=self.centralwidget)
        self.LHeader.setMinimumSize(QtCore.QSize(0, 100))
        self.LHeader.setMaximumSize(QtCore.QSize(16777215, 110))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.LHeader.setFont(font)
        self.LHeader.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.LHeader.setObjectName("LHeader")
        self.verticalLayout_2.addWidget(self.LHeader)
        self.person_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.person_label.setMinimumSize(QtCore.QSize(0, 40))
        self.person_label.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.person_label.setFont(font)
        self.person_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.person_label.setObjectName("person_label")
        self.verticalLayout_2.addWidget(self.person_label)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.scrollArea.setLineWidth(1)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 782, 305))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setContentsMargins(0, 0, 4, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.button_container = QtWidgets.QVBoxLayout()
        self.button_container.setObjectName("button_container")
        self.gridLayout.addLayout(self.button_container, 0, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        Teamselection.setCentralWidget(self.centralwidget)

        self.retranslateUi(Teamselection)
        QtCore.QMetaObject.connectSlotsByName(Teamselection)

    def retranslateUi(self, Teamselection):
        _translate = QtCore.QCoreApplication.translate
        Teamselection.setWindowTitle(_translate("Teamselection", "Select Team"))
        self.LHeader.setText(_translate("Teamselection", "Team auswählen"))
        self.LHeader.setProperty("cssClass", _translate("Teamselection", "neutral bold"))
        self.person_label.setText(_translate("Teamselection", "Scanned Name"))
        self.person_label.setProperty("cssClass", _translate("Teamselection", "bold"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Teamselection = QtWidgets.QMainWindow()
    ui = Ui_Teamselection()
    ui.setupUi(Teamselection)
    Teamselection.show()
    sys.exit(app.exec())
