# Form implementation generated from reading ui file 'wifiwindow.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WiFiWindow(object):
    def setupUi(self, WiFiWindow):
        WiFiWindow.setObjectName("WiFiWindow")
        WiFiWindow.resize(800, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WiFiWindow.sizePolicy().hasHeightForWidth())
        WiFiWindow.setSizePolicy(sizePolicy)
        WiFiWindow.setMinimumSize(QtCore.QSize(800, 480))
        WiFiWindow.setMaximumSize(QtCore.QSize(800, 480))
        WiFiWindow.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        WiFiWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=WiFiWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.button_back = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_back.setMaximumSize(QtCore.QSize(5000, 300))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.button_back.setFont(font)
        self.button_back.setObjectName("button_back")
        self.gridLayout.addWidget(self.button_back, 5, 0, 1, 1)
        self.button_enter = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_enter.setMaximumSize(QtCore.QSize(5000, 300))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.button_enter.setFont(font)
        self.button_enter.setObjectName("button_enter")
        self.gridLayout.addWidget(self.button_enter, 5, 1, 1, 1)
        self.input_ssid = ClickableLineEdit(parent=self.centralwidget)
        self.input_ssid.setMinimumSize(QtCore.QSize(0, 50))
        self.input_ssid.setMaximumSize(QtCore.QSize(16777215, 120))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.input_ssid.setFont(font)
        self.input_ssid.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.input_ssid.setObjectName("input_ssid")
        self.gridLayout.addWidget(self.input_ssid, 1, 0, 1, 2)
        self.label_ssid = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_ssid.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label_ssid.setFont(font)
        self.label_ssid.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_ssid.setObjectName("label_ssid")
        self.gridLayout.addWidget(self.label_ssid, 0, 0, 1, 2)
        self.label_password = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_password.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label_password.setFont(font)
        self.label_password.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_password.setObjectName("label_password")
        self.gridLayout.addWidget(self.label_password, 2, 0, 1, 2)
        self.input_password = ClickableLineEdit(parent=self.centralwidget)
        self.input_password.setMinimumSize(QtCore.QSize(0, 50))
        self.input_password.setMaximumSize(QtCore.QSize(16777215, 120))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.input_password.setFont(font)
        self.input_password.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.input_password.setObjectName("input_password")
        self.gridLayout.addWidget(self.input_password, 3, 0, 1, 2)
        WiFiWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(WiFiWindow)
        QtCore.QMetaObject.connectSlotsByName(WiFiWindow)

    def retranslateUi(self, WiFiWindow):
        _translate = QtCore.QCoreApplication.translate
        WiFiWindow.setWindowTitle(_translate("WiFiWindow", "Set Up WiFi"))
        self.button_back.setText(_translate("WiFiWindow", "< Back"))
        self.button_enter.setText(_translate("WiFiWindow", "Enter"))
        self.button_enter.setProperty("cssClass", _translate("WiFiWindow", "btn-inverted"))
        self.input_ssid.setProperty("cssClass", _translate("WiFiWindow", "bold"))
        self.label_ssid.setText(_translate("WiFiWindow", "SSID"))
        self.label_ssid.setProperty("cssClass", _translate("WiFiWindow", "secondary bold"))
        self.label_password.setText(_translate("WiFiWindow", "PASS"))
        self.label_password.setProperty("cssClass", _translate("WiFiWindow", "secondary bold"))
        self.input_password.setProperty("cssClass", _translate("WiFiWindow", "bold"))
from src.ui_elements.clickablelineedit import ClickableLineEdit


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WiFiWindow = QtWidgets.QMainWindow()
    ui = Ui_WiFiWindow()
    ui.setupUi(WiFiWindow)
    WiFiWindow.show()
    sys.exit(app.exec())
