version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    labels:
      - dependencies
      - skip-changelog
    schedule:
      interval: weekly
    cooldown:
      default-days: 3
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: uv
    directory: /
    labels:
      - dependencies
      - skip-changelog
    schedule:
      interval: weekly
    cooldown:
      default-days: 3
    groups:
      python:
        patterns:
          - "*"
  - package-ecosystem: npm
    directory: /web_client
    labels:
      - dependencies
      - skip-changelog
    schedule:
      interval: weekly
    cooldown:
      default-days: 3
    groups:
      npm:
        patterns:
          - "*"
