---
default_install_hook_types:
  - commit-msg
  - pre-commit
  - pre-push
exclude: ^(.*(\.?venv.*)/)
repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ☕️ Use Ruff to format code
        language: system
        types: [python]
        entry: uv run ruff format
        require_serial: true
      - id: ruff-linting
        name: ☕️ Use Ruff to lint code
        language: system
        types: [python]
        entry: uv run ruff check --fix
        require_serial: true
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-json
        name: ☕️ Check for JSON syntax errors
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck
        name: ☕️ Ensure Shell Scripts are good with ShellCheck
        files: .*\.sh$
        args: [-x, -e, SC1017]
