# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bottlewindow.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Bottlewindow(object):
    def setupUi(self, Bottlewindow):
        Bottlewindow.setObjectName("Bottlewindow")
        Bottlewindow.resize(800, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Bottlewindow.sizePolicy().hasHeightForWidth())
        Bottlewindow.setSizePolicy(sizePolicy)
        Bottlewindow.setMinimumSize(QtCore.QSize(800, 480))
        Bottlewindow.setMaximumSize(QtCore.QSize(800, 480))
        Bottlewindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Bottlewindow.setStyleSheet("QWidget\n"
"{\n"
"    color: rgb(0, 123, 255);    \n"
"    background-color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: rgb(97, 97, 97);\n"
"    color: rgb(255, 255, 255);\n"
"    border-width: 1px;\n"
"    border-color: rgb(97, 97, 97);\n"
"    border-style: solid;\n"
"    border-radius: 7;\n"
"    padding: 3px;\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"}\n"
"\n"
"QPushButton:checked\n"
"{\n"
"    color: rgb(255, 255, 255);    \n"
"    background-color: rgb(0, 123, 255);\n"
"}\n"
"\n"
"QProgressBar\n"
"{\n"
"    background-color: rgb(166, 166, 166);\n"
"    color: rgb(0, 0, 0);\n"
"    border: 2px rgb(166, 166, 166);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    border: 2px rgb(166, 166, 166);\n"
"    border-top-left-radius: 5px;\n"
"    border-bottom-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    border-bottom-right-radius: 5px;\n"
"    background-color: rgb(0, 123, 255);\n"
"   /* width: 40px;\n"
"    margin: 0.5px;*/\n"
"}\n"
"\n"
"#Labbruch {\n"
"    color: rgb(239, 151, 0);\n"
"}\n"
"#LName1 {\n"
"    color: rgb(239, 151, 0);\n"
"}\n"
"#LName2 {\n"
"    color: rgb(239, 151, 0);\n"
"}\n"
"#LName3 {\n"
"    color: rgb(239, 151, 0);\n"
"}\n"
"#LName4 {\n"
"    color: rgb(239, 151, 0);\n"
"}\n"
"#LName5 {\n"
"    color: rgb(239, 151, 0);\n"
"}\n"
"#LName6 {\n"
"    color: rgb(239, 151, 0);\n"
"}\n"
"#LName7 {\n"
"    color: rgb(239, 151, 0);\n"
"}\n"
"#LName8 {\n"
"    color: rgb(239, 151, 0);\n"
"}\n"
"#LName9 {\n"
"    color: rgb(239, 151, 0);\n"
"}\n"
"#LName10 {\n"
"    color: rgb(239, 151, 0);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(Bottlewindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LName1 = QtWidgets.QLabel(self.centralwidget)
        self.LName1.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.LName1.setFont(font)
        self.LName1.setObjectName("LName1")
        self.horizontalLayout.addWidget(self.LName1)
        self.PBMminus1 = QtWidgets.QPushButton(self.centralwidget)
        self.PBMminus1.setMinimumSize(QtCore.QSize(60, 20))
        self.PBMminus1.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.PBMminus1.setFont(font)
        self.PBMminus1.setObjectName("PBMminus1")
        self.horizontalLayout.addWidget(self.PBMminus1)
        self.LAmount1 = QtWidgets.QLabel(self.centralwidget)
        self.LAmount1.setMinimumSize(QtCore.QSize(65, 0))
        self.LAmount1.setMaximumSize(QtCore.QSize(175, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.LAmount1.setFont(font)
        self.LAmount1.setLineWidth(1)
        self.LAmount1.setAlignment(QtCore.Qt.AlignCenter)
        self.LAmount1.setObjectName("LAmount1")
        self.horizontalLayout.addWidget(self.LAmount1)
        self.PBMplus1 = QtWidgets.QPushButton(self.centralwidget)
        self.PBMplus1.setMinimumSize(QtCore.QSize(60, 20))
        self.PBMplus1.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.PBMplus1.setFont(font)
        self.PBMplus1.setObjectName("PBMplus1")
        self.horizontalLayout.addWidget(self.PBMplus1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.LName2 = QtWidgets.QLabel(self.centralwidget)
        self.LName2.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.LName2.setFont(font)
        self.LName2.setObjectName("LName2")
        self.horizontalLayout_2.addWidget(self.LName2)
        self.PBMminus2 = QtWidgets.QPushButton(self.centralwidget)
        self.PBMminus2.setMinimumSize(QtCore.QSize(60, 20))
        self.PBMminus2.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.PBMminus2.setFont(font)
        self.PBMminus2.setObjectName("PBMminus2")
        self.horizontalLayout_2.addWidget(self.PBMminus2)
        self.LAmount2 = QtWidgets.QLabel(self.centralwidget)
        self.LAmount2.setMinimumSize(QtCore.QSize(65, 0))
        self.LAmount2.setMaximumSize(QtCore.QSize(175, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.LAmount2.setFont(font)
        self.LAmount2.setLineWidth(1)
        self.LAmount2.setAlignment(QtCore.Qt.AlignCenter)
        self.LAmount2.setObjectName("LAmount2")
        self.horizontalLayout_2.addWidget(self.LAmount2)
        self.PBMplus2 = QtWidgets.QPushButton(self.centralwidget)
        self.PBMplus2.setMinimumSize(QtCore.QSize(60, 20))
        self.PBMplus2.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.PBMplus2.setFont(font)
        self.PBMplus2.setObjectName("PBMplus2")
        self.horizontalLayout_2.addWidget(self.PBMplus2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.LName3 = QtWidgets.QLabel(self.centralwidget)
        self.LName3.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.LName3.setFont(font)
        self.LName3.setObjectName("LName3")
        self.horizontalLayout_3.addWidget(self.LName3)
        self.PBMminus3 = QtWidgets.QPushButton(self.centralwidget)
        self.PBMminus3.setMinimumSize(QtCore.QSize(60, 20))
        self.PBMminus3.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.PBMminus3.setFont(font)
        self.PBMminus3.setObjectName("PBMminus3")
        self.horizontalLayout_3.addWidget(self.PBMminus3)
        self.LAmount3 = QtWidgets.QLabel(self.centralwidget)
        self.LAmount3.setMinimumSize(QtCore.QSize(65, 0))
        self.LAmount3.setMaximumSize(QtCore.QSize(175, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.LAmount3.setFont(font)
        self.LAmount3.setLineWidth(1)
        self.LAmount3.setAlignment(QtCore.Qt.AlignCenter)
        self.LAmount3.setObjectName("LAmount3")
        self.horizontalLayout_3.addWidget(self.LAmount3)
        self.PBMplus3 = QtWidgets.QPushButton(self.centralwidget)
        self.PBMplus3.setMinimumSize(QtCore.QSize(60, 20))
        self.PBMplus3.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.PBMplus3.setFont(font)
        self.PBMplus3.setObjectName("PBMplus3")
        self.horizontalLayout_3.addWidget(self.PBMplus3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.LName4 = QtWidgets.QLabel(self.centralwidget)
        self.LName4.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.LName4.setFont(font)
        self.LName4.setObjectName("LName4")
        self.horizontalLayout_4.addWidget(self.LName4)
        self.PBMminus4 = QtWidgets.QPushButton(self.centralwidget)
        self.PBMminus4.setMinimumSize(QtCore.QSize(60, 20))
        self.PBMminus4.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.PBMminus4.setFont(font)
        self.PBMminus4.setObjectName("PBMminus4")
        self.horizontalLayout_4.addWidget(self.PBMminus4)
        self.LAmount4 = QtWidgets.QLabel(self.centralwidget)
        self.LAmount4.setMinimumSize(QtCore.QSize(65, 0))
        self.LAmount4.setMaximumSize(QtCore.QSize(175, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.LAmount4.setFont(font)
        self.LAmount4.setLineWidth(1)
        self.LAmount4.setAlignment(QtCore.Qt.AlignCenter)
        self.LAmount4.setObjectName("LAmount4")
        self.horizontalLayout_4.addWidget(self.LAmount4)
        self.PBMplus4 = QtWidgets.QPushButton(self.centralwidget)
        self.PBMplus4.setMinimumSize(QtCore.QSize(60, 20))
        self.PBMplus4.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.PBMplus4.setFont(font)
        self.PBMplus4.setObjectName("PBMplus4")
        self.horizontalLayout_4.addWidget(self.PBMplus4)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.LName5 = QtWidgets.QLabel(self.centralwidget)
        self.LName5.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.LName5.setFont(font)
        self.LName5.setObjectName("LName5")
        self.horizontalLayout_5.addWidget(self.LName5)
        self.PBMminus5 = QtWidgets.QPushButton(self.centralwidget)
        self.PBMminus5.setMinimumSize(QtCore.QSize(60, 20))
        self.PBMminus5.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.PBMminus5.setFont(font)
        self.PBMminus5.setObjectName("PBMminus5")
        self.horizontalLayout_5.addWidget(self.PBMminus5)
        self.LAmount5 = QtWidgets.QLabel(self.centralwidget)
        self.LAmount5.setMinimumSize(QtCore.QSize(65, 0))
        self.LAmount5.setMaximumSize(QtCore.QSize(175, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.LAmount5.setFont(font)
        self.LAmount5.setLineWidth(1)
        self.LAmount5.setAlignment(QtCore.Qt.AlignCenter)
        self.LAmount5.setObjectName("LAmount5")
        self.horizontalLayout_5.addWidget(self.LAmount5)
        self.PBMplus5 = QtWidgets.QPushButton(self.centralwidget)
        self.PBMplus5.setMinimumSize(QtCore.QSize(60, 20))
        self.PBMplus5.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.PBMplus5.setFont(font)
        self.PBMplus5.setObjectName("PBMplus5")
        self.horizontalLayout_5.addWidget(self.PBMplus5)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.LName6 = QtWidgets.QLabel(self.centralwidget)
        self.LName6.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.LName6.setFont(font)
        self.LName6.setObjectName("LName6")
        self.horizontalLayout_6.addWidget(self.LName6)
        self.PBMminus6 = QtWidgets.QPushButton(self.centralwidget)
        self.PBMminus6.setMinimumSize(QtCore.QSize(60, 20))
        self.PBMminus6.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.PBMminus6.setFont(font)
        self.PBMminus6.setObjectName("PBMminus6")
        self.horizontalLayout_6.addWidget(self.PBMminus6)
        self.LAmount6 = QtWidgets.QLabel(self.centralwidget)
        self.LAmount6.setMinimumSize(QtCore.QSize(65, 0))
        self.LAmount6.setMaximumSize(QtCore.QSize(175, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.LAmount6.setFont(font)
        self.LAmount6.setLineWidth(1)
        self.LAmount6.setAlignment(QtCore.Qt.AlignCenter)
        self.LAmount6.setObjectName("LAmount6")
        self.horizontalLayout_6.addWidget(self.LAmount6)
        self.PBMplus6 = QtWidgets.QPushButton(self.centralwidget)
        self.PBMplus6.setMinimumSize(QtCore.QSize(60, 20))
        self.PBMplus6.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.PBMplus6.setFont(font)
        self.PBMplus6.setObjectName("PBMplus6")
        self.horizontalLayout_6.addWidget(self.PBMplus6)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.LName7 = QtWidgets.QLabel(self.centralwidget)
        self.LName7.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.LName7.setFont(font)
        self.LName7.setObjectName("LName7")
        self.horizontalLayout_7.addWidget(self.LName7)
        self.PBMminus7 = QtWidgets.QPushButton(self.centralwidget)
        self.PBMminus7.setMinimumSize(QtCore.QSize(60, 20))
        self.PBMminus7.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.PBMminus7.setFont(font)
        self.PBMminus7.setObjectName("PBMminus7")
        self.horizontalLayout_7.addWidget(self.PBMminus7)
        self.LAmount7 = QtWidgets.QLabel(self.centralwidget)
        self.LAmount7.setMinimumSize(QtCore.QSize(65, 0))
        self.LAmount7.setMaximumSize(QtCore.QSize(175, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.LAmount7.setFont(font)
        self.LAmount7.setLineWidth(1)
        self.LAmount7.setAlignment(QtCore.Qt.AlignCenter)
        self.LAmount7.setObjectName("LAmount7")
        self.horizontalLayout_7.addWidget(self.LAmount7)
        self.PBMplus7 = QtWidgets.QPushButton(self.centralwidget)
        self.PBMplus7.setMinimumSize(QtCore.QSize(60, 20))
        self.PBMplus7.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.PBMplus7.setFont(font)
        self.PBMplus7.setObjectName("PBMplus7")
        self.horizontalLayout_7.addWidget(self.PBMplus7)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.LName8 = QtWidgets.QLabel(self.centralwidget)
        self.LName8.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.LName8.setFont(font)
        self.LName8.setObjectName("LName8")
        self.horizontalLayout_8.addWidget(self.LName8)
        self.PBMminus8 = QtWidgets.QPushButton(self.centralwidget)
        self.PBMminus8.setMinimumSize(QtCore.QSize(60, 20))
        self.PBMminus8.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.PBMminus8.setFont(font)
        self.PBMminus8.setObjectName("PBMminus8")
        self.horizontalLayout_8.addWidget(self.PBMminus8)
        self.LAmount8 = QtWidgets.QLabel(self.centralwidget)
        self.LAmount8.setMinimumSize(QtCore.QSize(65, 0))
        self.LAmount8.setMaximumSize(QtCore.QSize(175, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.LAmount8.setFont(font)
        self.LAmount8.setLineWidth(1)
        self.LAmount8.setAlignment(QtCore.Qt.AlignCenter)
        self.LAmount8.setObjectName("LAmount8")
        self.horizontalLayout_8.addWidget(self.LAmount8)
        self.PBMplus8 = QtWidgets.QPushButton(self.centralwidget)
        self.PBMplus8.setMinimumSize(QtCore.QSize(60, 20))
        self.PBMplus8.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.PBMplus8.setFont(font)
        self.PBMplus8.setObjectName("PBMplus8")
        self.horizontalLayout_8.addWidget(self.PBMplus8)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.LName9 = QtWidgets.QLabel(self.centralwidget)
        self.LName9.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.LName9.setFont(font)
        self.LName9.setObjectName("LName9")
        self.horizontalLayout_9.addWidget(self.LName9)
        self.PBMminus9 = QtWidgets.QPushButton(self.centralwidget)
        self.PBMminus9.setMinimumSize(QtCore.QSize(60, 20))
        self.PBMminus9.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.PBMminus9.setFont(font)
        self.PBMminus9.setObjectName("PBMminus9")
        self.horizontalLayout_9.addWidget(self.PBMminus9)
        self.LAmount9 = QtWidgets.QLabel(self.centralwidget)
        self.LAmount9.setMinimumSize(QtCore.QSize(65, 0))
        self.LAmount9.setMaximumSize(QtCore.QSize(175, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.LAmount9.setFont(font)
        self.LAmount9.setLineWidth(1)
        self.LAmount9.setAlignment(QtCore.Qt.AlignCenter)
        self.LAmount9.setObjectName("LAmount9")
        self.horizontalLayout_9.addWidget(self.LAmount9)
        self.PBMplus9 = QtWidgets.QPushButton(self.centralwidget)
        self.PBMplus9.setMinimumSize(QtCore.QSize(60, 20))
        self.PBMplus9.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.PBMplus9.setFont(font)
        self.PBMplus9.setObjectName("PBMplus9")
        self.horizontalLayout_9.addWidget(self.PBMplus9)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.LName10 = QtWidgets.QLabel(self.centralwidget)
        self.LName10.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.LName10.setFont(font)
        self.LName10.setObjectName("LName10")
        self.horizontalLayout_10.addWidget(self.LName10)
        self.PBMminus10 = QtWidgets.QPushButton(self.centralwidget)
        self.PBMminus10.setMinimumSize(QtCore.QSize(60, 20))
        self.PBMminus10.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.PBMminus10.setFont(font)
        self.PBMminus10.setObjectName("PBMminus10")
        self.horizontalLayout_10.addWidget(self.PBMminus10)
        self.LAmount10 = QtWidgets.QLabel(self.centralwidget)
        self.LAmount10.setMinimumSize(QtCore.QSize(65, 0))
        self.LAmount10.setMaximumSize(QtCore.QSize(175, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.LAmount10.setFont(font)
        self.LAmount10.setLineWidth(1)
        self.LAmount10.setAlignment(QtCore.Qt.AlignCenter)
        self.LAmount10.setObjectName("LAmount10")
        self.horizontalLayout_10.addWidget(self.LAmount10)
        self.PBMplus10 = QtWidgets.QPushButton(self.centralwidget)
        self.PBMplus10.setMinimumSize(QtCore.QSize(60, 20))
        self.PBMplus10.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.PBMplus10.setFont(font)
        self.PBMplus10.setObjectName("PBMplus10")
        self.horizontalLayout_10.addWidget(self.PBMplus10)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.PBEintragen = QtWidgets.QPushButton(self.centralwidget)
        self.PBEintragen.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.PBEintragen.setFont(font)
        self.PBEintragen.setObjectName("PBEintragen")
        self.horizontalLayout_11.addWidget(self.PBEintragen)
        self.PBAbbrechen = QtWidgets.QPushButton(self.centralwidget)
        self.PBAbbrechen.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.PBAbbrechen.setFont(font)
        self.PBAbbrechen.setObjectName("PBAbbrechen")
        self.horizontalLayout_11.addWidget(self.PBAbbrechen)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        Bottlewindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(Bottlewindow)
        QtCore.QMetaObject.connectSlotsByName(Bottlewindow)

    def retranslateUi(self, Bottlewindow):
        _translate = QtCore.QCoreApplication.translate
        Bottlewindow.setWindowTitle(_translate("Bottlewindow", "~~ Füllstand der Flaschen auswählen ~~"))
        self.LName1.setText(_translate("Bottlewindow", "TextLabel"))
        self.PBMminus1.setText(_translate("Bottlewindow", "-"))
        self.LAmount1.setText(_translate("Bottlewindow", "200"))
        self.PBMplus1.setText(_translate("Bottlewindow", "+"))
        self.LName2.setText(_translate("Bottlewindow", "TextLabel"))
        self.PBMminus2.setText(_translate("Bottlewindow", "-"))
        self.LAmount2.setText(_translate("Bottlewindow", "200"))
        self.PBMplus2.setText(_translate("Bottlewindow", "+"))
        self.LName3.setText(_translate("Bottlewindow", "TextLabel"))
        self.PBMminus3.setText(_translate("Bottlewindow", "-"))
        self.LAmount3.setText(_translate("Bottlewindow", "200"))
        self.PBMplus3.setText(_translate("Bottlewindow", "+"))
        self.LName4.setText(_translate("Bottlewindow", "TextLabel"))
        self.PBMminus4.setText(_translate("Bottlewindow", "-"))
        self.LAmount4.setText(_translate("Bottlewindow", "200"))
        self.PBMplus4.setText(_translate("Bottlewindow", "+"))
        self.LName5.setText(_translate("Bottlewindow", "TextLabel"))
        self.PBMminus5.setText(_translate("Bottlewindow", "-"))
        self.LAmount5.setText(_translate("Bottlewindow", "200"))
        self.PBMplus5.setText(_translate("Bottlewindow", "+"))
        self.LName6.setText(_translate("Bottlewindow", "TextLabel"))
        self.PBMminus6.setText(_translate("Bottlewindow", "-"))
        self.LAmount6.setText(_translate("Bottlewindow", "200"))
        self.PBMplus6.setText(_translate("Bottlewindow", "+"))
        self.LName7.setText(_translate("Bottlewindow", "TextLabel"))
        self.PBMminus7.setText(_translate("Bottlewindow", "-"))
        self.LAmount7.setText(_translate("Bottlewindow", "200"))
        self.PBMplus7.setText(_translate("Bottlewindow", "+"))
        self.LName8.setText(_translate("Bottlewindow", "TextLabel"))
        self.PBMminus8.setText(_translate("Bottlewindow", "-"))
        self.LAmount8.setText(_translate("Bottlewindow", "200"))
        self.PBMplus8.setText(_translate("Bottlewindow", "+"))
        self.LName9.setText(_translate("Bottlewindow", "TextLabel"))
        self.PBMminus9.setText(_translate("Bottlewindow", "-"))
        self.LAmount9.setText(_translate("Bottlewindow", "200"))
        self.PBMplus9.setText(_translate("Bottlewindow", "+"))
        self.LName10.setText(_translate("Bottlewindow", "TextLabel"))
        self.PBMminus10.setText(_translate("Bottlewindow", "-"))
        self.LAmount10.setText(_translate("Bottlewindow", "200"))
        self.PBMplus10.setText(_translate("Bottlewindow", "+"))
        self.PBEintragen.setText(_translate("Bottlewindow", "Eintragen"))
        self.PBAbbrechen.setText(_translate("Bottlewindow", "Abbrechen"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Bottlewindow = QtWidgets.QMainWindow()
    ui = Ui_Bottlewindow()
    ui.setupUi(Bottlewindow)
    Bottlewindow.show()
    sys.exit(app.exec_())

