@startuml AddonSchema
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!define FONTAWESOMEOLD https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome

!include DEVICONS/linux.puml
!include DEVICONS/python.puml
!include DEVICONS/sqllite.puml
!include DEVICONS/aptana.puml
!include DEVICONS/docker.puml
!include DEVICONS/html5.puml
!include FONTAWESOME/users.puml
!include FONTAWESOME/user.puml
!include FONTAWESOMEOLD/send_o.puml

skinparam backgroundColor #fff
!pragma ratio 0.6

HIDE_STEREOTYPE()

together {
System(before_cocktail, "before_cocktail", "Executed before the cocktail")
System(after_cocktail, "after_cocktail", "Executed right after the cocktail")
}

System_Boundary(c1, "CocktailBerry") {
  Container(gui, "Options", "python", "User clicks on addon GUI")
  ' together {
  Container(main, "Program Start", "python", "CocktailBerry starts and set everything up")
  Container(cocktail, "Cocktail Preparation", "python", "CocktailBerry prepares the Cocktail")
  Container(end, "Program End", "python", "User exits the program")
  ' }

}
System(setup, "setup", "Executed at program start")
System(build_addon_gui, "build_addon_gui", "When User want to do addition things")
System(cleanup, "cleanup", "Executed at program end")

Rel_D(main, cocktail, "")
Rel_D(main, gui, "")
Rel_D(cocktail, end, "")

Rel_D(before_cocktail, cocktail, "Can interrup")
Rel_L(cocktail, after_cocktail, "Triggers")
Rel_L(setup, main, "Add Settings")
Rel_R(end, cleanup, "Triggers")
Rel_R(gui, build_addon_gui, "Triggers")

Rel(before_cocktail, after_cocktail, "")

@enduml