# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Cocktailmanager_2.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(800, 480))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setStyleSheet("QWidget\n"
"{\n"
"    color: rgb(0, 123, 255);    \n"
"    background-color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"\n"
"QWidget:item:selected\n"
"{\n"
"    color: rgb(239, 151, 0);\n"
"    border: 1px solid rgb(239, 151, 0);\n"
"    /*color: rgb(255, 255, 255);    \n"
"    background-color: rgb(0, 123, 255);    */\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: 1px solid  rgb(97, 97, 97);\n"
"    top: 1px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background-color: rgb(97, 97, 97);\n"
"    color: rgb(255, 255, 255);\n"
"    border-width: 1px;\n"
"    border-color: rgb(255, 255, 255);\n"
"    border-style: solid;\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    padding: 5px;\n"
"    padding-left: 63px;\n"
"    padding-right:63px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    color: rgb(255, 255, 255);    \n"
"    background-color: rgb(0, 123, 255);\n"
"}\n"
"\n"
".QMessageBox {font-size: 16pt}\n"
"\n"
".QSlider {\n"
"    min-height: 30px;\n"
"    max-height: 50px;\n"
"}\n"
"\n"
".QSlider::groove:horizontal {\n"
"    border: 1px solid;\n"
"    height: 5px;\n"
"    background: #393939;\n"
"    margin: 0 12px;\n"
"}\n"
"\n"
".QSlider::handle:horizontal {\n"
"    background: rgb(0, 123, 255);\n"
"    width: 30px;\n"
"    height: 30px;\n"
"    margin: -24px -12px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: rgb(97, 97, 97);\n"
"    color: rgb(255, 255, 255);\n"
"    border-width: 1px;\n"
"    border-color: rgb(97, 97, 97);\n"
"    border-style: solid;\n"
"    border-radius: 7;\n"
"    padding: 3px;\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"}\n"
"\n"
"QPushButton:checked\n"
"{\n"
"    color: rgb(255, 255, 255);    \n"
"    background-color: rgb(0, 123, 255);\n"
"    border-color: rgb(0, 123, 255);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    color: rgb(255, 255, 255);    \n"
"    background-color: rgb(0, 123, 255);\n"
"    border-color: rgb(0, 123, 255);\n"
"}\n"
"\n"
"QProgressBar\n"
"{\n"
"    background-color: rgb(166, 166, 166);\n"
"    color: rgb(0, 0, 0);\n"
"    border: 2px rgb(166, 166, 166);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    border: 2px rgb(166, 166, 166);\n"
"    border-top-left-radius: 5px;\n"
"    border-bottom-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    border-bottom-right-radius: 5px;\n"
"    background-color: rgb(0, 123, 255);\n"
"   /* width: 40px;\n"
"    margin: 0.5px;*/\n"
"}\n"
"\n"
"QComboBox {\n"
"    color: rgb(0, 123, 255);    \n"
"    border: 1px solid  rgb(97, 97, 97);\n"
"    border-top-left-radius: 7px;\n"
"    border-bottom-left-radius: 7px;\n"
"    padding: 1px 18px 1px 5px;\n"
"    min-width: 6em;\n"
"}\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"    border: 1px solid  rgb(97, 97, 97);\n"
"    border-top-left-radius: 7px;\n"
"    border-bottom-left-radius: 0px;\n"
"    color: rgb(239, 151, 0);\n"
"}\n"
"\n"
"/* QComboBox:hover\n"
"{\n"
"    color: rgb(239, 151, 0);\n"
"}*/\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid  rgb(97, 97, 97);\n"
"}\n"
"\n"
"/*QComboBox:item:checked {\n"
"    color: rgb(239, 151, 0);\n"
"    border: 1px solid rgb(239, 151, 0);\n"
"}\n"
"\n"
"QComboBox:item:selected {\n"
"    color: rgb(239, 151, 0);\n"
"    border: 1px solid rgb(239, 151, 0);\n"
"} */\n"
"\n"
"QLineEdit\n"
"{\n"
"    padding: 1px;\n"
"    border-style: solid;\n"
"    border: 1px solid rgb(97, 97, 97);\n"
"    border-radius: 5;\n"
"}\n"
"\n"
"\n"
"#TBelegung {\n"
"    border: 1px solid  rgb(97, 97, 97);\n"
"}\n"
"\n"
"#LWMaker {\n"
"    border: 1px solid  rgb(97, 97, 97);\n"
"}\n"
"\n"
"#LEGehaltRezept{\n"
"    color: rgb(239, 151, 0);\n"
"}\n"
"\n"
"#LEZutatRezept{\n"
"    color: rgb(239, 151, 0);\n"
"}\n"
"\n"
"#LAlkoholgehalt{\n"
"    color: rgb(239, 151, 0);\n"
"}\n"
"\n"
"#LKommentar{\n"
"    color: rgb(211, 211, 211);\n"
"}\n"
"\n"
"#LAlkoholname{\n"
"    color: rgb(170, 170, 170);\n"
"}\n"
"\n"
"#LECocktail{\n"
"    color: rgb(239, 151, 0);\n"
"}\n"
"\n"
"#LEFlaschenvolumen{\n"
"    color: rgb(239, 151, 0);\n"
"}\n"
"\n"
"#MakerLMenge{\n"
"    color:rgb(255, 255, 255);\n"
"}\n"
"\n"
"#LMZutat1 {\n"
"    color: rgb(239, 151, 0);\n"
"}\n"
"#LMZutat2 {\n"
"    color: rgb(239, 151, 0);\n"
"}\n"
"#LMZutat3 {\n"
"    color: rgb(239, 151, 0);\n"
"}\n"
"#LMZutat4 {\n"
"    color: rgb(239, 151, 0);\n"
"}\n"
"#LMZutat5 {\n"
"    color: rgb(239, 151, 0);\n"
"}\n"
"#LMZutat6 {\n"
"    color: rgb(239, 151, 0);\n"
"}\n"
"#LMZutat7 {\n"
"    color: rgb(239, 151, 0);\n"
"}\n"
"#LMZutat8 {\n"
"    color: rgb(239, 151, 0);\n"
"}\n"
"#LMZutat9 {\n"
"    color: rgb(239, 151, 0);\n"
"}\n"
"#LMZutat10 {\n"
"    color: rgb(239, 151, 0);\n"
"}\n"
"#LER1 {\n"
"    color: rgb(239, 151, 0);\n"
"}\n"
"#LER2 {\n"
"    color: rgb(239, 151, 0);\n"
"}\n"
"#LER3 {\n"
"    color: rgb(239, 151, 0);\n"
"}\n"
"#LER4 {\n"
"    color: rgb(239, 151, 0);\n"
"}\n"
"#LER5 {\n"
"    color: rgb(239, 151, 0);\n"
"}\n"
"#LER6 {\n"
"    color: rgb(239, 151, 0);\n"
"}\n"
"#LER7 {\n"
"    color: rgb(239, 151, 0);\n"
"}\n"
"#LER8 {\n"
"    color: rgb(239, 151, 0);\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.LWMaker = QtWidgets.QListWidget(self.tab)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.LWMaker.setFont(font)
        self.LWMaker.setStyleSheet(" QScrollBar:vertical {\n"
"     border: 1px solid rgb(97, 97, 97);\n"
"     background: rgb(0, 0, 0);\n"
"     width: 40px;\n"
"     margin: 41px 0 41px 0;\n"
" }\n"
" QScrollBar::handle:vertical {\n"
"     background: rgb(0, 0, 0);\n"
"     min-width: 20px;\n"
"     max-width: 100px;\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"     border: 1px solid rgb(97, 97, 97);\n"
"     background: rgb(0, 0, 0);\n"
"     height: 40px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
"\n"
" QScrollBar::sub-line:vertical {\n"
"     border: 1px solid rgb(97, 97, 97);\n"
"     background: rgb(0, 0, 0);\n"
"     height: 40px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
"/*\n"
" QScrollBar::sub-page:vertical {\n"
"    height: 100px\n"
"} */\n"
"\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"        width: 12px;\n"
"     height: 12px;\n"
"     background: rgb(0, 123, 255);\n"
" }")
        self.LWMaker.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.LWMaker.setTextElideMode(QtCore.Qt.ElideRight)
        self.LWMaker.setObjectName("LWMaker")
        self.verticalLayout_21.addWidget(self.LWMaker)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.PBSetnull = QtWidgets.QPushButton(self.tab)
        self.PBSetnull.setMinimumSize(QtCore.QSize(60, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.PBSetnull.setFont(font)
        self.PBSetnull.setObjectName("PBSetnull")
        self.horizontalLayout_21.addWidget(self.PBSetnull)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem)
        self.label_17 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_21.addWidget(self.label_17)
        self.HSIntensity = QtWidgets.QSlider(self.tab)
        self.HSIntensity.setMinimumSize(QtCore.QSize(250, 30))
        self.HSIntensity.setMaximumSize(QtCore.QSize(400, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.HSIntensity.setFont(font)
        self.HSIntensity.setMinimum(-20)
        self.HSIntensity.setMaximum(20)
        self.HSIntensity.setSingleStep(2)
        self.HSIntensity.setPageStep(2)
        self.HSIntensity.setProperty("value", 0)
        self.HSIntensity.setOrientation(QtCore.Qt.Horizontal)
        self.HSIntensity.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.HSIntensity.setObjectName("HSIntensity")
        self.horizontalLayout_21.addWidget(self.HSIntensity)
        self.label_24 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_21.addWidget(self.label_24)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem1)
        self.verticalLayout_21.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_2.addLayout(self.verticalLayout_21)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.LAlkoholname = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.LAlkoholname.setFont(font)
        self.LAlkoholname.setAlignment(QtCore.Qt.AlignCenter)
        self.LAlkoholname.setObjectName("LAlkoholname")
        self.verticalLayout_3.addWidget(self.LAlkoholname)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.LMenge = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.LMenge.setFont(font)
        self.LMenge.setAlignment(QtCore.Qt.AlignCenter)
        self.LMenge.setObjectName("LMenge")
        self.horizontalLayout_19.addWidget(self.LMenge)
        self.LAlkoholgehalt = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.LAlkoholgehalt.setFont(font)
        self.LAlkoholgehalt.setAlignment(QtCore.Qt.AlignCenter)
        self.LAlkoholgehalt.setObjectName("LAlkoholgehalt")
        self.horizontalLayout_19.addWidget(self.LAlkoholgehalt)
        self.verticalLayout_3.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.LZutat1 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.LZutat1.setFont(font)
        self.LZutat1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LZutat1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LZutat1.setObjectName("LZutat1")
        self.verticalLayout_6.addWidget(self.LZutat1)
        self.LZutat2 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.LZutat2.setFont(font)
        self.LZutat2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LZutat2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LZutat2.setObjectName("LZutat2")
        self.verticalLayout_6.addWidget(self.LZutat2)
        self.LZutat3 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.LZutat3.setFont(font)
        self.LZutat3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LZutat3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LZutat3.setObjectName("LZutat3")
        self.verticalLayout_6.addWidget(self.LZutat3)
        self.LZutat4 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.LZutat4.setFont(font)
        self.LZutat4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LZutat4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LZutat4.setObjectName("LZutat4")
        self.verticalLayout_6.addWidget(self.LZutat4)
        self.LZutat5 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.LZutat5.setFont(font)
        self.LZutat5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LZutat5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LZutat5.setObjectName("LZutat5")
        self.verticalLayout_6.addWidget(self.LZutat5)
        self.LZutat6 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.LZutat6.setFont(font)
        self.LZutat6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LZutat6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LZutat6.setObjectName("LZutat6")
        self.verticalLayout_6.addWidget(self.LZutat6)
        self.LZutat7 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.LZutat7.setFont(font)
        self.LZutat7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LZutat7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LZutat7.setObjectName("LZutat7")
        self.verticalLayout_6.addWidget(self.LZutat7)
        self.LZutat8 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.LZutat8.setFont(font)
        self.LZutat8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LZutat8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LZutat8.setObjectName("LZutat8")
        self.verticalLayout_6.addWidget(self.LZutat8)
        self.LZutat9 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.LZutat9.setFont(font)
        self.LZutat9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LZutat9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LZutat9.setObjectName("LZutat9")
        self.verticalLayout_6.addWidget(self.LZutat9)
        self.LZutat10 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.LZutat10.setFont(font)
        self.LZutat10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LZutat10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LZutat10.setObjectName("LZutat10")
        self.verticalLayout_6.addWidget(self.LZutat10)
        self.horizontalLayout_6.addLayout(self.verticalLayout_6)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.LMZutat1 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.LMZutat1.setFont(font)
        self.LMZutat1.setObjectName("LMZutat1")
        self.verticalLayout_5.addWidget(self.LMZutat1)
        self.LMZutat2 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.LMZutat2.setFont(font)
        self.LMZutat2.setObjectName("LMZutat2")
        self.verticalLayout_5.addWidget(self.LMZutat2)
        self.LMZutat3 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.LMZutat3.setFont(font)
        self.LMZutat3.setObjectName("LMZutat3")
        self.verticalLayout_5.addWidget(self.LMZutat3)
        self.LMZutat4 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.LMZutat4.setFont(font)
        self.LMZutat4.setObjectName("LMZutat4")
        self.verticalLayout_5.addWidget(self.LMZutat4)
        self.LMZutat5 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.LMZutat5.setFont(font)
        self.LMZutat5.setObjectName("LMZutat5")
        self.verticalLayout_5.addWidget(self.LMZutat5)
        self.LMZutat6 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.LMZutat6.setFont(font)
        self.LMZutat6.setObjectName("LMZutat6")
        self.verticalLayout_5.addWidget(self.LMZutat6)
        self.LMZutat7 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.LMZutat7.setFont(font)
        self.LMZutat7.setObjectName("LMZutat7")
        self.verticalLayout_5.addWidget(self.LMZutat7)
        self.LMZutat8 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.LMZutat8.setFont(font)
        self.LMZutat8.setObjectName("LMZutat8")
        self.verticalLayout_5.addWidget(self.LMZutat8)
        self.LMZutat9 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.LMZutat9.setFont(font)
        self.LMZutat9.setObjectName("LMZutat9")
        self.verticalLayout_5.addWidget(self.LMZutat9)
        self.LMZutat10 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.LMZutat10.setFont(font)
        self.LMZutat10.setObjectName("LMZutat10")
        self.verticalLayout_5.addWidget(self.LMZutat10)
        self.horizontalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.PBMminus = QtWidgets.QPushButton(self.tab)
        self.PBMminus.setMinimumSize(QtCore.QSize(60, 40))
        self.PBMminus.setMaximumSize(QtCore.QSize(60, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.PBMminus.setFont(font)
        self.PBMminus.setObjectName("PBMminus")
        self.horizontalLayout_7.addWidget(self.PBMminus)
        self.LCustomMenge = QtWidgets.QLabel(self.tab)
        self.LCustomMenge.setMinimumSize(QtCore.QSize(65, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.LCustomMenge.setFont(font)
        self.LCustomMenge.setLineWidth(1)
        self.LCustomMenge.setAlignment(QtCore.Qt.AlignCenter)
        self.LCustomMenge.setObjectName("LCustomMenge")
        self.horizontalLayout_7.addWidget(self.LCustomMenge)
        self.PBMplus = QtWidgets.QPushButton(self.tab)
        self.PBMplus.setMinimumSize(QtCore.QSize(60, 40))
        self.PBMplus.setMaximumSize(QtCore.QSize(60, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.PBMplus.setFont(font)
        self.PBMplus.setObjectName("PBMplus")
        self.horizontalLayout_7.addWidget(self.PBMplus)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.PBZubereiten_custom = QtWidgets.QPushButton(self.tab)
        self.PBZubereiten_custom.setMinimumSize(QtCore.QSize(150, 40))
        self.PBZubereiten_custom.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.PBZubereiten_custom.setFont(font)
        self.PBZubereiten_custom.setObjectName("PBZubereiten_custom")
        self.horizontalLayout_7.addWidget(self.PBZubereiten_custom)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.LWZutaten = QtWidgets.QListWidget(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.LWZutaten.setFont(font)
        self.LWZutaten.setStyleSheet(" QScrollBar:vertical {\n"
"     border: 1px solid rgb(97, 97, 97);\n"
"     background: rgb(0, 0, 0);\n"
"     width: 30px;\n"
"     margin: 31px 0 31px 0;\n"
" }\n"
" QScrollBar::handle:vertical {\n"
"     background: rgb(0, 0, 0);\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"     border: 1px solid rgb(97, 97, 97);\n"
"     background: rgb(0, 0, 0);\n"
"     height: 30px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
"\n"
" QScrollBar::sub-line:vertical {\n"
"     border: 1px solid rgb(97, 97, 97);\n"
"     background: rgb(0, 0, 0);\n"
"     height: 30px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
"\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"        width: 10px;\n"
"     height: 10px;\n"
"     background: rgb(0, 123, 255);\n"
" }")
        self.LWZutaten.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.LWZutaten.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.LWZutaten.setObjectName("LWZutaten")
        self.horizontalLayout_9.addWidget(self.LWZutaten)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_9.addWidget(self.label)
        self.LEZutatRezept = ClickableLineEdit(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LEZutatRezept.setFont(font)
        self.LEZutatRezept.setObjectName("LEZutatRezept")
        self.verticalLayout_9.addWidget(self.LEZutatRezept)
        self.verticalLayout_8.addLayout(self.verticalLayout_9)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_11.addWidget(self.label_2)
        self.LEGehaltRezept = ClickableLineEdit(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LEGehaltRezept.setFont(font)
        self.LEGehaltRezept.setObjectName("LEGehaltRezept")
        self.verticalLayout_11.addWidget(self.LEGehaltRezept)
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_11.addWidget(self.label_13)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.verticalLayout_11.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.PBZminus = QtWidgets.QPushButton(self.tab_2)
        self.PBZminus.setMinimumSize(QtCore.QSize(80, 29))
        self.PBZminus.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.PBZminus.setFont(font)
        self.PBZminus.setObjectName("PBZminus")
        self.horizontalLayout_20.addWidget(self.PBZminus)
        self.LEFlaschenvolumen = QtWidgets.QLineEdit(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LEFlaschenvolumen.setFont(font)
        self.LEFlaschenvolumen.setObjectName("LEFlaschenvolumen")
        self.horizontalLayout_20.addWidget(self.LEFlaschenvolumen)
        self.PBZplus = QtWidgets.QPushButton(self.tab_2)
        self.PBZplus.setMinimumSize(QtCore.QSize(80, 29))
        self.PBZplus.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.PBZplus.setFont(font)
        self.PBZplus.setObjectName("PBZplus")
        self.horizontalLayout_20.addWidget(self.PBZplus)
        self.verticalLayout_11.addLayout(self.horizontalLayout_20)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem4)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem5)
        self.PBZeinzelnd = QtWidgets.QPushButton(self.tab_2)
        self.PBZeinzelnd.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.PBZeinzelnd.setFont(font)
        self.PBZeinzelnd.setObjectName("PBZeinzelnd")
        self.horizontalLayout_22.addWidget(self.PBZeinzelnd)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem6)
        self.verticalLayout_11.addLayout(self.horizontalLayout_22)
        spacerItem7 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_11.addItem(spacerItem7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.PBZclear = QtWidgets.QPushButton(self.tab_2)
        self.PBZclear.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.PBZclear.setFont(font)
        self.PBZclear.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PBZclear.setObjectName("PBZclear")
        self.horizontalLayout_5.addWidget(self.PBZclear)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.PBZnull = QtWidgets.QPushButton(self.tab_2)
        self.PBZnull.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.PBZnull.setFont(font)
        self.PBZnull.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PBZnull.setObjectName("PBZnull")
        self.horizontalLayout_5.addWidget(self.PBZnull)
        self.verticalLayout_11.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.PBZdelete = QtWidgets.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.PBZdelete.setFont(font)
        self.PBZdelete.setObjectName("PBZdelete")
        self.horizontalLayout_13.addWidget(self.PBZdelete)
        self.LEpw2 = ClickableLineEdit(self.tab_2)
        self.LEpw2.setMinimumSize(QtCore.QSize(0, 29))
        self.LEpw2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.LEpw2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.LEpw2.setObjectName("LEpw2")
        self.horizontalLayout_13.addWidget(self.LEpw2)
        self.PBZaktualisieren = QtWidgets.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.PBZaktualisieren.setFont(font)
        self.PBZaktualisieren.setObjectName("PBZaktualisieren")
        self.horizontalLayout_13.addWidget(self.PBZaktualisieren)
        self.PBZutathinzu = QtWidgets.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.PBZutathinzu.setFont(font)
        self.PBZutathinzu.setObjectName("PBZutathinzu")
        self.horizontalLayout_13.addWidget(self.PBZutathinzu)
        self.verticalLayout_11.addLayout(self.horizontalLayout_13)
        self.verticalLayout_8.addLayout(self.verticalLayout_11)
        self.horizontalLayout_11.addLayout(self.verticalLayout_8)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_8)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_23 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_15.addWidget(self.label_23)
        self.LECocktail = ClickableLineEdit(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LECocktail.setFont(font)
        self.LECocktail.setPlaceholderText("")
        self.LECocktail.setObjectName("LECocktail")
        self.horizontalLayout_15.addWidget(self.LECocktail)
        self.PBenable = QtWidgets.QPushButton(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.PBenable.setFont(font)
        self.PBenable.setObjectName("PBenable")
        self.horizontalLayout_15.addWidget(self.PBenable)
        self.PBRnull = QtWidgets.QPushButton(self.tab_3)
        self.PBRnull.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.PBRnull.setFont(font)
        self.PBRnull.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PBRnull.setObjectName("PBRnull")
        self.horizontalLayout_15.addWidget(self.PBRnull)
        self.verticalLayout_17.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.CBR1 = QtWidgets.QComboBox(self.tab_3)
        self.CBR1.setMinimumSize(QtCore.QSize(103, 28))
        self.CBR1.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.CBR1.setFont(font)
        self.CBR1.setObjectName("CBR1")
        self.verticalLayout_4.addWidget(self.CBR1)
        self.CBR2 = QtWidgets.QComboBox(self.tab_3)
        self.CBR2.setMinimumSize(QtCore.QSize(103, 28))
        self.CBR2.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.CBR2.setFont(font)
        self.CBR2.setObjectName("CBR2")
        self.verticalLayout_4.addWidget(self.CBR2)
        self.CBR3 = QtWidgets.QComboBox(self.tab_3)
        self.CBR3.setMinimumSize(QtCore.QSize(103, 28))
        self.CBR3.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.CBR3.setFont(font)
        self.CBR3.setObjectName("CBR3")
        self.verticalLayout_4.addWidget(self.CBR3)
        self.CBR4 = QtWidgets.QComboBox(self.tab_3)
        self.CBR4.setMinimumSize(QtCore.QSize(103, 28))
        self.CBR4.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.CBR4.setFont(font)
        self.CBR4.setObjectName("CBR4")
        self.verticalLayout_4.addWidget(self.CBR4)
        self.CBR5 = QtWidgets.QComboBox(self.tab_3)
        self.CBR5.setMinimumSize(QtCore.QSize(103, 28))
        self.CBR5.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.CBR5.setFont(font)
        self.CBR5.setObjectName("CBR5")
        self.verticalLayout_4.addWidget(self.CBR5)
        self.CBR6 = QtWidgets.QComboBox(self.tab_3)
        self.CBR6.setMinimumSize(QtCore.QSize(103, 28))
        self.CBR6.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.CBR6.setFont(font)
        self.CBR6.setObjectName("CBR6")
        self.verticalLayout_4.addWidget(self.CBR6)
        self.CBR7 = QtWidgets.QComboBox(self.tab_3)
        self.CBR7.setMinimumSize(QtCore.QSize(103, 28))
        self.CBR7.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.CBR7.setFont(font)
        self.CBR7.setObjectName("CBR7")
        self.verticalLayout_4.addWidget(self.CBR7)
        self.CBR8 = QtWidgets.QComboBox(self.tab_3)
        self.CBR8.setMinimumSize(QtCore.QSize(103, 28))
        self.CBR8.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.CBR8.setFont(font)
        self.CBR8.setObjectName("CBR8")
        self.verticalLayout_4.addWidget(self.CBR8)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem9)
        self.CHBenabled = QtWidgets.QCheckBox(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CHBenabled.setFont(font)
        self.CHBenabled.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.CHBenabled.setChecked(True)
        self.CHBenabled.setObjectName("CHBenabled")
        self.verticalLayout_4.addWidget(self.CHBenabled)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem10)
        self.PBclear = QtWidgets.QPushButton(self.tab_3)
        self.PBclear.setMinimumSize(QtCore.QSize(0, 33))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.PBclear.setFont(font)
        self.PBclear.setObjectName("PBclear")
        self.verticalLayout_4.addWidget(self.PBclear)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.LER1 = ClickableLineEdit(self.tab_3)
        self.LER1.setMinimumSize(QtCore.QSize(0, 28))
        self.LER1.setMaximumSize(QtCore.QSize(100, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LER1.setFont(font)
        self.LER1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LER1.setObjectName("LER1")
        self.verticalLayout_16.addWidget(self.LER1)
        self.LER2 = ClickableLineEdit(self.tab_3)
        self.LER2.setMinimumSize(QtCore.QSize(0, 28))
        self.LER2.setMaximumSize(QtCore.QSize(100, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LER2.setFont(font)
        self.LER2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LER2.setObjectName("LER2")
        self.verticalLayout_16.addWidget(self.LER2)
        self.LER3 = ClickableLineEdit(self.tab_3)
        self.LER3.setMinimumSize(QtCore.QSize(0, 28))
        self.LER3.setMaximumSize(QtCore.QSize(100, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LER3.setFont(font)
        self.LER3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LER3.setObjectName("LER3")
        self.verticalLayout_16.addWidget(self.LER3)
        self.LER4 = ClickableLineEdit(self.tab_3)
        self.LER4.setMinimumSize(QtCore.QSize(0, 28))
        self.LER4.setMaximumSize(QtCore.QSize(100, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LER4.setFont(font)
        self.LER4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LER4.setObjectName("LER4")
        self.verticalLayout_16.addWidget(self.LER4)
        self.LER5 = ClickableLineEdit(self.tab_3)
        self.LER5.setMinimumSize(QtCore.QSize(0, 28))
        self.LER5.setMaximumSize(QtCore.QSize(100, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LER5.setFont(font)
        self.LER5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LER5.setObjectName("LER5")
        self.verticalLayout_16.addWidget(self.LER5)
        self.LER6 = ClickableLineEdit(self.tab_3)
        self.LER6.setMinimumSize(QtCore.QSize(0, 28))
        self.LER6.setMaximumSize(QtCore.QSize(100, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LER6.setFont(font)
        self.LER6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LER6.setObjectName("LER6")
        self.verticalLayout_16.addWidget(self.LER6)
        self.LER7 = ClickableLineEdit(self.tab_3)
        self.LER7.setMinimumSize(QtCore.QSize(0, 28))
        self.LER7.setMaximumSize(QtCore.QSize(100, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LER7.setFont(font)
        self.LER7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LER7.setObjectName("LER7")
        self.verticalLayout_16.addWidget(self.LER7)
        self.LER8 = ClickableLineEdit(self.tab_3)
        self.LER8.setMinimumSize(QtCore.QSize(0, 28))
        self.LER8.setMaximumSize(QtCore.QSize(100, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LER8.setFont(font)
        self.LER8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LER8.setObjectName("LER8")
        self.verticalLayout_16.addWidget(self.LER8)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_16.addItem(spacerItem11)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem12)
        self.LEmenge_a = ClickableLineEdit(self.tab_3)
        self.LEmenge_a.setMaximumSize(QtCore.QSize(100, 16777215))
        self.LEmenge_a.setObjectName("LEmenge_a")
        self.verticalLayout_16.addWidget(self.LEmenge_a)
        self.horizontalLayout_16.addLayout(self.verticalLayout_16)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_7 = QtWidgets.QLabel(self.tab_3)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_18.addWidget(self.label_7)
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_18.addWidget(self.label_5)
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_18.addWidget(self.label_9)
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_18.addWidget(self.label_8)
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_18.addWidget(self.label_3)
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_18.addWidget(self.label_6)
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_18.addWidget(self.label_10)
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_18.addWidget(self.label_4)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_18.addItem(spacerItem13)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_18.addItem(spacerItem14)
        self.LEprozent_a = ClickableLineEdit(self.tab_3)
        self.LEprozent_a.setMaximumSize(QtCore.QSize(100, 16777215))
        self.LEprozent_a.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.LEprozent_a.setObjectName("LEprozent_a")
        self.verticalLayout_18.addWidget(self.LEprozent_a)
        self.horizontalLayout_16.addLayout(self.verticalLayout_18)
        self.verticalLayout_12.addLayout(self.horizontalLayout_16)
        self.LEKommentar = ClickableLineEdit(self.tab_3)
        self.LEKommentar.setObjectName("LEKommentar")
        self.verticalLayout_12.addWidget(self.LEKommentar)
        self.horizontalLayout_3.addLayout(self.verticalLayout_12)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.LWRezepte = QtWidgets.QListWidget(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.LWRezepte.setFont(font)
        self.LWRezepte.setStyleSheet(" QScrollBar:vertical {\n"
"     border: 1px solid rgb(97, 97, 97);\n"
"     background: rgb(0, 0, 0);\n"
"     width: 30px;\n"
"     margin: 31px 0 31px 0;\n"
" }\n"
" QScrollBar::handle:vertical {\n"
"     background: rgb(0, 0, 0);\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"     border: 1px solid rgb(97, 97, 97);\n"
"     background: rgb(0, 0, 0);\n"
"     height: 30px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
"\n"
" QScrollBar::sub-line:vertical {\n"
"     border: 1px solid rgb(97, 97, 97);\n"
"     background: rgb(0, 0, 0);\n"
"     height: 30px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
"\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"        width: 10px;\n"
"     height: 10px;\n"
"     background: rgb(0, 123, 255);\n"
" }")
        self.LWRezepte.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.LWRezepte.setObjectName("LWRezepte")
        self.verticalLayout_10.addWidget(self.LWRezepte)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.PBdelete = QtWidgets.QPushButton(self.tab_3)
        self.PBdelete.setMinimumSize(QtCore.QSize(0, 33))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.PBdelete.setFont(font)
        self.PBdelete.setObjectName("PBdelete")
        self.horizontalLayout_10.addWidget(self.PBdelete)
        self.LEpw = ClickableLineEdit(self.tab_3)
        self.LEpw.setMinimumSize(QtCore.QSize(0, 29))
        self.LEpw.setMaximumSize(QtCore.QSize(50, 16777215))
        self.LEpw.setEchoMode(QtWidgets.QLineEdit.Password)
        self.LEpw.setObjectName("LEpw")
        self.horizontalLayout_10.addWidget(self.LEpw)
        self.PBRezeptaktualisieren = QtWidgets.QPushButton(self.tab_3)
        self.PBRezeptaktualisieren.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.PBRezeptaktualisieren.setFont(font)
        self.PBRezeptaktualisieren.setObjectName("PBRezeptaktualisieren")
        self.horizontalLayout_10.addWidget(self.PBRezeptaktualisieren)
        self.PBRezepthinzu = QtWidgets.QPushButton(self.tab_3)
        self.PBRezepthinzu.setMinimumSize(QtCore.QSize(0, 32))
        self.PBRezepthinzu.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.PBRezepthinzu.setFont(font)
        self.PBRezepthinzu.setObjectName("PBRezepthinzu")
        self.horizontalLayout_10.addWidget(self.PBRezepthinzu)
        self.verticalLayout_10.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_3.addLayout(self.verticalLayout_10)
        self.verticalLayout_17.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_17)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.tab_4)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem15)
        self.PBneu1 = QtWidgets.QPushButton(self.tab_4)
        self.PBneu1.setMinimumSize(QtCore.QSize(50, 29))
        self.PBneu1.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.PBneu1.setFont(font)
        self.PBneu1.setCheckable(True)
        self.PBneu1.setChecked(False)
        self.PBneu1.setObjectName("PBneu1")
        self.verticalLayout_15.addWidget(self.PBneu1)
        self.PBneu2 = QtWidgets.QPushButton(self.tab_4)
        self.PBneu2.setMinimumSize(QtCore.QSize(50, 29))
        self.PBneu2.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.PBneu2.setFont(font)
        self.PBneu2.setCheckable(True)
        self.PBneu2.setObjectName("PBneu2")
        self.verticalLayout_15.addWidget(self.PBneu2)
        self.PBneu3 = QtWidgets.QPushButton(self.tab_4)
        self.PBneu3.setMinimumSize(QtCore.QSize(50, 29))
        self.PBneu3.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.PBneu3.setFont(font)
        self.PBneu3.setCheckable(True)
        self.PBneu3.setObjectName("PBneu3")
        self.verticalLayout_15.addWidget(self.PBneu3)
        self.PBneu4 = QtWidgets.QPushButton(self.tab_4)
        self.PBneu4.setMinimumSize(QtCore.QSize(50, 29))
        self.PBneu4.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.PBneu4.setFont(font)
        self.PBneu4.setCheckable(True)
        self.PBneu4.setObjectName("PBneu4")
        self.verticalLayout_15.addWidget(self.PBneu4)
        self.PBneu5 = QtWidgets.QPushButton(self.tab_4)
        self.PBneu5.setMinimumSize(QtCore.QSize(50, 29))
        self.PBneu5.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.PBneu5.setFont(font)
        self.PBneu5.setCheckable(True)
        self.PBneu5.setObjectName("PBneu5")
        self.verticalLayout_15.addWidget(self.PBneu5)
        self.PBneu6 = QtWidgets.QPushButton(self.tab_4)
        self.PBneu6.setMinimumSize(QtCore.QSize(50, 29))
        self.PBneu6.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.PBneu6.setFont(font)
        self.PBneu6.setCheckable(True)
        self.PBneu6.setObjectName("PBneu6")
        self.verticalLayout_15.addWidget(self.PBneu6)
        self.PBneu7 = QtWidgets.QPushButton(self.tab_4)
        self.PBneu7.setMinimumSize(QtCore.QSize(50, 29))
        self.PBneu7.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.PBneu7.setFont(font)
        self.PBneu7.setCheckable(True)
        self.PBneu7.setObjectName("PBneu7")
        self.verticalLayout_15.addWidget(self.PBneu7)
        self.PBneu8 = QtWidgets.QPushButton(self.tab_4)
        self.PBneu8.setMinimumSize(QtCore.QSize(50, 29))
        self.PBneu8.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.PBneu8.setFont(font)
        self.PBneu8.setCheckable(True)
        self.PBneu8.setObjectName("PBneu8")
        self.verticalLayout_15.addWidget(self.PBneu8)
        self.PBneu9 = QtWidgets.QPushButton(self.tab_4)
        self.PBneu9.setMinimumSize(QtCore.QSize(50, 29))
        self.PBneu9.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.PBneu9.setFont(font)
        self.PBneu9.setCheckable(True)
        self.PBneu9.setObjectName("PBneu9")
        self.verticalLayout_15.addWidget(self.PBneu9)
        self.PBneu10 = QtWidgets.QPushButton(self.tab_4)
        self.PBneu10.setMinimumSize(QtCore.QSize(50, 29))
        self.PBneu10.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.PBneu10.setFont(font)
        self.PBneu10.setCheckable(True)
        self.PBneu10.setObjectName("PBneu10")
        self.verticalLayout_15.addWidget(self.PBneu10)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem16)
        self.horizontalLayout_14.addLayout(self.verticalLayout_15)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem17)
        self.LBelegung1 = QtWidgets.QLabel(self.tab_4)
        self.LBelegung1.setMinimumSize(QtCore.QSize(120, 29))
        self.LBelegung1.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LBelegung1.setFont(font)
        self.LBelegung1.setStyleSheet("    color: rgb(239, 151, 0);")
        self.LBelegung1.setObjectName("LBelegung1")
        self.verticalLayout_7.addWidget(self.LBelegung1)
        self.LBelegung2 = QtWidgets.QLabel(self.tab_4)
        self.LBelegung2.setMinimumSize(QtCore.QSize(120, 29))
        self.LBelegung2.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LBelegung2.setFont(font)
        self.LBelegung2.setStyleSheet("    color: rgb(239, 151, 0);")
        self.LBelegung2.setObjectName("LBelegung2")
        self.verticalLayout_7.addWidget(self.LBelegung2)
        self.LBelegung3 = QtWidgets.QLabel(self.tab_4)
        self.LBelegung3.setMinimumSize(QtCore.QSize(120, 29))
        self.LBelegung3.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LBelegung3.setFont(font)
        self.LBelegung3.setStyleSheet("    color: rgb(239, 151, 0);")
        self.LBelegung3.setObjectName("LBelegung3")
        self.verticalLayout_7.addWidget(self.LBelegung3)
        self.LBelegung4 = QtWidgets.QLabel(self.tab_4)
        self.LBelegung4.setMinimumSize(QtCore.QSize(120, 29))
        self.LBelegung4.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LBelegung4.setFont(font)
        self.LBelegung4.setStyleSheet("    color: rgb(239, 151, 0);")
        self.LBelegung4.setObjectName("LBelegung4")
        self.verticalLayout_7.addWidget(self.LBelegung4)
        self.LBelegung5 = QtWidgets.QLabel(self.tab_4)
        self.LBelegung5.setMinimumSize(QtCore.QSize(120, 29))
        self.LBelegung5.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LBelegung5.setFont(font)
        self.LBelegung5.setStyleSheet("    color: rgb(239, 151, 0);")
        self.LBelegung5.setObjectName("LBelegung5")
        self.verticalLayout_7.addWidget(self.LBelegung5)
        self.LBelegung6 = QtWidgets.QLabel(self.tab_4)
        self.LBelegung6.setMinimumSize(QtCore.QSize(120, 29))
        self.LBelegung6.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LBelegung6.setFont(font)
        self.LBelegung6.setStyleSheet("    color: rgb(239, 151, 0);")
        self.LBelegung6.setObjectName("LBelegung6")
        self.verticalLayout_7.addWidget(self.LBelegung6)
        self.LBelegung7 = QtWidgets.QLabel(self.tab_4)
        self.LBelegung7.setMinimumSize(QtCore.QSize(120, 29))
        self.LBelegung7.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LBelegung7.setFont(font)
        self.LBelegung7.setStyleSheet("    color: rgb(239, 151, 0);")
        self.LBelegung7.setObjectName("LBelegung7")
        self.verticalLayout_7.addWidget(self.LBelegung7)
        self.LBelegung8 = QtWidgets.QLabel(self.tab_4)
        self.LBelegung8.setMinimumSize(QtCore.QSize(120, 29))
        self.LBelegung8.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LBelegung8.setFont(font)
        self.LBelegung8.setStyleSheet("    color: rgb(239, 151, 0);")
        self.LBelegung8.setObjectName("LBelegung8")
        self.verticalLayout_7.addWidget(self.LBelegung8)
        self.LBelegung9 = QtWidgets.QLabel(self.tab_4)
        self.LBelegung9.setMinimumSize(QtCore.QSize(120, 29))
        self.LBelegung9.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LBelegung9.setFont(font)
        self.LBelegung9.setStyleSheet("    color: rgb(239, 151, 0);")
        self.LBelegung9.setObjectName("LBelegung9")
        self.verticalLayout_7.addWidget(self.LBelegung9)
        self.LBelegung10 = QtWidgets.QLabel(self.tab_4)
        self.LBelegung10.setMinimumSize(QtCore.QSize(120, 29))
        self.LBelegung10.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LBelegung10.setFont(font)
        self.LBelegung10.setStyleSheet("    color: rgb(239, 151, 0);")
        self.LBelegung10.setObjectName("LBelegung10")
        self.verticalLayout_7.addWidget(self.LBelegung10)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem18)
        self.horizontalLayout_14.addLayout(self.verticalLayout_7)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem19)
        self.ProBBelegung1 = QtWidgets.QProgressBar(self.tab_4)
        self.ProBBelegung1.setMinimumSize(QtCore.QSize(250, 29))
        self.ProBBelegung1.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ProBBelegung1.setFont(font)
        self.ProBBelegung1.setProperty("value", 24)
        self.ProBBelegung1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ProBBelegung1.setObjectName("ProBBelegung1")
        self.verticalLayout_19.addWidget(self.ProBBelegung1)
        self.ProBBelegung2 = QtWidgets.QProgressBar(self.tab_4)
        self.ProBBelegung2.setMinimumSize(QtCore.QSize(250, 29))
        self.ProBBelegung2.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ProBBelegung2.setFont(font)
        self.ProBBelegung2.setProperty("value", 24)
        self.ProBBelegung2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ProBBelegung2.setObjectName("ProBBelegung2")
        self.verticalLayout_19.addWidget(self.ProBBelegung2)
        self.ProBBelegung3 = QtWidgets.QProgressBar(self.tab_4)
        self.ProBBelegung3.setMinimumSize(QtCore.QSize(250, 29))
        self.ProBBelegung3.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ProBBelegung3.setFont(font)
        self.ProBBelegung3.setProperty("value", 24)
        self.ProBBelegung3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ProBBelegung3.setObjectName("ProBBelegung3")
        self.verticalLayout_19.addWidget(self.ProBBelegung3)
        self.ProBBelegung4 = QtWidgets.QProgressBar(self.tab_4)
        self.ProBBelegung4.setMinimumSize(QtCore.QSize(250, 29))
        self.ProBBelegung4.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ProBBelegung4.setFont(font)
        self.ProBBelegung4.setProperty("value", 24)
        self.ProBBelegung4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ProBBelegung4.setObjectName("ProBBelegung4")
        self.verticalLayout_19.addWidget(self.ProBBelegung4)
        self.ProBBelegung5 = QtWidgets.QProgressBar(self.tab_4)
        self.ProBBelegung5.setMinimumSize(QtCore.QSize(250, 29))
        self.ProBBelegung5.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ProBBelegung5.setFont(font)
        self.ProBBelegung5.setProperty("value", 24)
        self.ProBBelegung5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ProBBelegung5.setObjectName("ProBBelegung5")
        self.verticalLayout_19.addWidget(self.ProBBelegung5)
        self.ProBBelegung6 = QtWidgets.QProgressBar(self.tab_4)
        self.ProBBelegung6.setMinimumSize(QtCore.QSize(250, 29))
        self.ProBBelegung6.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ProBBelegung6.setFont(font)
        self.ProBBelegung6.setProperty("value", 24)
        self.ProBBelegung6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ProBBelegung6.setObjectName("ProBBelegung6")
        self.verticalLayout_19.addWidget(self.ProBBelegung6)
        self.ProBBelegung7 = QtWidgets.QProgressBar(self.tab_4)
        self.ProBBelegung7.setMinimumSize(QtCore.QSize(250, 29))
        self.ProBBelegung7.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ProBBelegung7.setFont(font)
        self.ProBBelegung7.setProperty("value", 24)
        self.ProBBelegung7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ProBBelegung7.setObjectName("ProBBelegung7")
        self.verticalLayout_19.addWidget(self.ProBBelegung7)
        self.ProBBelegung8 = QtWidgets.QProgressBar(self.tab_4)
        self.ProBBelegung8.setMinimumSize(QtCore.QSize(250, 29))
        self.ProBBelegung8.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ProBBelegung8.setFont(font)
        self.ProBBelegung8.setProperty("value", 24)
        self.ProBBelegung8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ProBBelegung8.setObjectName("ProBBelegung8")
        self.verticalLayout_19.addWidget(self.ProBBelegung8)
        self.ProBBelegung9 = QtWidgets.QProgressBar(self.tab_4)
        self.ProBBelegung9.setMinimumSize(QtCore.QSize(250, 29))
        self.ProBBelegung9.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ProBBelegung9.setFont(font)
        self.ProBBelegung9.setProperty("value", 24)
        self.ProBBelegung9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ProBBelegung9.setObjectName("ProBBelegung9")
        self.verticalLayout_19.addWidget(self.ProBBelegung9)
        self.ProBBelegung10 = QtWidgets.QProgressBar(self.tab_4)
        self.ProBBelegung10.setMinimumSize(QtCore.QSize(250, 29))
        self.ProBBelegung10.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ProBBelegung10.setFont(font)
        self.ProBBelegung10.setProperty("value", 24)
        self.ProBBelegung10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ProBBelegung10.setObjectName("ProBBelegung10")
        self.verticalLayout_19.addWidget(self.ProBBelegung10)
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem20)
        self.horizontalLayout_14.addLayout(self.verticalLayout_19)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.PBFlanwenden = QtWidgets.QPushButton(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.PBFlanwenden.setFont(font)
        self.PBFlanwenden.setObjectName("PBFlanwenden")
        self.verticalLayout_2.addWidget(self.PBFlanwenden)
        self.horizontalLayout_12.addLayout(self.verticalLayout_2)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem21)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        spacerItem22 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem22)
        self.CBB1 = QtWidgets.QComboBox(self.tab_4)
        self.CBB1.setMinimumSize(QtCore.QSize(103, 29))
        self.CBB1.setMaximumSize(QtCore.QSize(200, 29))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.CBB1.setFont(font)
        self.CBB1.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.CBB1.setMaxVisibleItems(11)
        self.CBB1.setObjectName("CBB1")
        self.verticalLayout_13.addWidget(self.CBB1)
        self.CBB2 = QtWidgets.QComboBox(self.tab_4)
        self.CBB2.setMinimumSize(QtCore.QSize(103, 29))
        self.CBB2.setMaximumSize(QtCore.QSize(200, 29))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.CBB2.setFont(font)
        self.CBB2.setMaxVisibleItems(11)
        self.CBB2.setObjectName("CBB2")
        self.verticalLayout_13.addWidget(self.CBB2)
        self.CBB3 = QtWidgets.QComboBox(self.tab_4)
        self.CBB3.setMinimumSize(QtCore.QSize(103, 29))
        self.CBB3.setMaximumSize(QtCore.QSize(200, 29))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.CBB3.setFont(font)
        self.CBB3.setMaxVisibleItems(11)
        self.CBB3.setObjectName("CBB3")
        self.verticalLayout_13.addWidget(self.CBB3)
        self.CBB4 = QtWidgets.QComboBox(self.tab_4)
        self.CBB4.setMinimumSize(QtCore.QSize(103, 29))
        self.CBB4.setMaximumSize(QtCore.QSize(200, 29))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.CBB4.setFont(font)
        self.CBB4.setMaxVisibleItems(11)
        self.CBB4.setObjectName("CBB4")
        self.verticalLayout_13.addWidget(self.CBB4)
        self.CBB5 = QtWidgets.QComboBox(self.tab_4)
        self.CBB5.setMinimumSize(QtCore.QSize(103, 29))
        self.CBB5.setMaximumSize(QtCore.QSize(200, 29))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.CBB5.setFont(font)
        self.CBB5.setMaxVisibleItems(11)
        self.CBB5.setObjectName("CBB5")
        self.verticalLayout_13.addWidget(self.CBB5)
        self.CBB6 = QtWidgets.QComboBox(self.tab_4)
        self.CBB6.setMinimumSize(QtCore.QSize(103, 29))
        self.CBB6.setMaximumSize(QtCore.QSize(200, 29))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.CBB6.setFont(font)
        self.CBB6.setMaxVisibleItems(11)
        self.CBB6.setObjectName("CBB6")
        self.verticalLayout_13.addWidget(self.CBB6)
        self.CBB7 = QtWidgets.QComboBox(self.tab_4)
        self.CBB7.setMinimumSize(QtCore.QSize(103, 29))
        self.CBB7.setMaximumSize(QtCore.QSize(200, 29))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.CBB7.setFont(font)
        self.CBB7.setMaxVisibleItems(11)
        self.CBB7.setObjectName("CBB7")
        self.verticalLayout_13.addWidget(self.CBB7)
        self.CBB8 = QtWidgets.QComboBox(self.tab_4)
        self.CBB8.setMinimumSize(QtCore.QSize(103, 29))
        self.CBB8.setMaximumSize(QtCore.QSize(200, 29))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.CBB8.setFont(font)
        self.CBB8.setMaxVisibleItems(11)
        self.CBB8.setObjectName("CBB8")
        self.verticalLayout_13.addWidget(self.CBB8)
        self.CBB9 = QtWidgets.QComboBox(self.tab_4)
        self.CBB9.setMinimumSize(QtCore.QSize(103, 29))
        self.CBB9.setMaximumSize(QtCore.QSize(200, 29))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.CBB9.setFont(font)
        self.CBB9.setMaxVisibleItems(11)
        self.CBB9.setObjectName("CBB9")
        self.verticalLayout_13.addWidget(self.CBB9)
        self.CBB10 = QtWidgets.QComboBox(self.tab_4)
        self.CBB10.setMinimumSize(QtCore.QSize(103, 29))
        self.CBB10.setMaximumSize(QtCore.QSize(200, 29))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.CBB10.setFont(font)
        self.CBB10.setMaxVisibleItems(11)
        self.CBB10.setObjectName("CBB10")
        self.verticalLayout_13.addWidget(self.CBB10)
        spacerItem23 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem23)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.PBBelegung = QtWidgets.QPushButton(self.tab_4)
        self.PBBelegung.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.PBBelegung.setFont(font)
        self.PBBelegung.setObjectName("PBBelegung")
        self.horizontalLayout_18.addWidget(self.PBBelegung)
        self.LECleanMachine = ClickableLineEdit(self.tab_4)
        self.LECleanMachine.setMinimumSize(QtCore.QSize(0, 29))
        self.LECleanMachine.setMaximumSize(QtCore.QSize(50, 16777215))
        self.LECleanMachine.setEchoMode(QtWidgets.QLineEdit.Password)
        self.LECleanMachine.setObjectName("LECleanMachine")
        self.horizontalLayout_18.addWidget(self.LECleanMachine)
        self.verticalLayout_13.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_12.addLayout(self.verticalLayout_13)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        spacerItem24 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem24)
        self.label_11 = QtWidgets.QLabel(self.tab_4)
        self.label_11.setMinimumSize(QtCore.QSize(0, 29))
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("    color: rgb(239, 151, 0);")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_14.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.tab_4)
        self.label_12.setMinimumSize(QtCore.QSize(0, 29))
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("    color: rgb(239, 151, 0);")
        self.label_12.setObjectName("label_12")
        self.verticalLayout_14.addWidget(self.label_12)
        self.label_14 = QtWidgets.QLabel(self.tab_4)
        self.label_14.setMinimumSize(QtCore.QSize(0, 29))
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("    color: rgb(239, 151, 0);")
        self.label_14.setObjectName("label_14")
        self.verticalLayout_14.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(self.tab_4)
        self.label_15.setMinimumSize(QtCore.QSize(0, 29))
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("    color: rgb(239, 151, 0);")
        self.label_15.setObjectName("label_15")
        self.verticalLayout_14.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.tab_4)
        self.label_16.setMinimumSize(QtCore.QSize(0, 29))
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("    color: rgb(239, 151, 0);")
        self.label_16.setObjectName("label_16")
        self.verticalLayout_14.addWidget(self.label_16)
        self.label_22 = QtWidgets.QLabel(self.tab_4)
        self.label_22.setMinimumSize(QtCore.QSize(0, 29))
        self.label_22.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("    color: rgb(239, 151, 0);")
        self.label_22.setObjectName("label_22")
        self.verticalLayout_14.addWidget(self.label_22)
        self.label_18 = QtWidgets.QLabel(self.tab_4)
        self.label_18.setMinimumSize(QtCore.QSize(0, 29))
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("    color: rgb(239, 151, 0);")
        self.label_18.setObjectName("label_18")
        self.verticalLayout_14.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.tab_4)
        self.label_19.setMinimumSize(QtCore.QSize(0, 29))
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("    color: rgb(239, 151, 0);")
        self.label_19.setObjectName("label_19")
        self.verticalLayout_14.addWidget(self.label_19)
        self.label_21 = QtWidgets.QLabel(self.tab_4)
        self.label_21.setMinimumSize(QtCore.QSize(0, 29))
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("    color: rgb(239, 151, 0);")
        self.label_21.setObjectName("label_21")
        self.verticalLayout_14.addWidget(self.label_21)
        self.label_20 = QtWidgets.QLabel(self.tab_4)
        self.label_20.setMinimumSize(QtCore.QSize(0, 29))
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("    color: rgb(239, 151, 0);")
        self.label_20.setObjectName("label_20")
        self.verticalLayout_14.addWidget(self.label_20)
        spacerItem25 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem25)
        self.PBCleanMachine = QtWidgets.QPushButton(self.tab_4)
        self.PBCleanMachine.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.PBCleanMachine.setFont(font)
        self.PBCleanMachine.setObjectName("PBCleanMachine")
        self.verticalLayout_14.addWidget(self.PBCleanMachine)
        self.horizontalLayout_12.addLayout(self.verticalLayout_14)
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionCocktailmaker = QtWidgets.QAction(MainWindow)
        self.actionCocktailmaker.setObjectName("actionCocktailmaker")
        self.actionZutatenmanager = QtWidgets.QAction(MainWindow)
        self.actionZutatenmanager.setObjectName("actionZutatenmanager")
        self.actionSlotbelegung = QtWidgets.QAction(MainWindow)
        self.actionSlotbelegung.setObjectName("actionSlotbelegung")
        self.actionRezeptverwalter = QtWidgets.QAction(MainWindow)
        self.actionRezeptverwalter.setObjectName("actionRezeptverwalter")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cocktailmanager"))
        self.LWMaker.setSortingEnabled(True)
        self.PBSetnull.setText(_translate("MainWindow", "O"))
        self.label_17.setText(_translate("MainWindow", "-"))
        self.label_24.setText(_translate("MainWindow", "+"))
        self.LAlkoholname.setText(_translate("MainWindow", "LAlkoholname"))
        self.LMenge.setText(_translate("MainWindow", "Menge in ml"))
        self.LAlkoholgehalt.setText(_translate("MainWindow", "Alk in %"))
        self.LZutat1.setText(_translate("MainWindow", "LZutat1"))
        self.LZutat2.setText(_translate("MainWindow", "LZutat2"))
        self.LZutat3.setText(_translate("MainWindow", "LZutat3"))
        self.LZutat4.setText(_translate("MainWindow", "LZutat4"))
        self.LZutat5.setText(_translate("MainWindow", "LZutat5"))
        self.LZutat6.setText(_translate("MainWindow", "LZutat6"))
        self.LZutat7.setText(_translate("MainWindow", "LZutat7"))
        self.LZutat8.setText(_translate("MainWindow", "LZutat8"))
        self.LZutat9.setText(_translate("MainWindow", "LZutat9"))
        self.LZutat10.setText(_translate("MainWindow", "LZutat10"))
        self.LMZutat1.setText(_translate("MainWindow", "LMZutat1"))
        self.LMZutat2.setText(_translate("MainWindow", "LMZutat2"))
        self.LMZutat3.setText(_translate("MainWindow", "LMZutat3"))
        self.LMZutat4.setText(_translate("MainWindow", "LMZutat4"))
        self.LMZutat5.setText(_translate("MainWindow", "LMZutat5"))
        self.LMZutat6.setText(_translate("MainWindow", "LMZutat6"))
        self.LMZutat7.setText(_translate("MainWindow", "LMZutat7"))
        self.LMZutat8.setText(_translate("MainWindow", "LMZutat8"))
        self.LMZutat9.setText(_translate("MainWindow", "LMZutat9"))
        self.LMZutat10.setText(_translate("MainWindow", "LMZutat10"))
        self.PBMminus.setText(_translate("MainWindow", "-"))
        self.LCustomMenge.setText(_translate("MainWindow", "200"))
        self.PBMplus.setText(_translate("MainWindow", "+"))
        self.PBZubereiten_custom.setText(_translate("MainWindow", "Zubereiten"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Maker"))
        self.LWZutaten.setSortingEnabled(True)
        self.label.setText(_translate("MainWindow", "Zutat"))
        self.label_2.setText(_translate("MainWindow", "Alkoholgehalt"))
        self.label_13.setText(_translate("MainWindow", "Flaschenvolume (ml)"))
        self.PBZminus.setText(_translate("MainWindow", "-"))
        self.PBZplus.setText(_translate("MainWindow", "+"))
        self.PBZeinzelnd.setText(_translate("MainWindow", "Einzelne Zutat ausgeben"))
        self.PBZclear.setText(_translate("MainWindow", "clear"))
        self.PBZnull.setText(_translate("MainWindow", "export + null"))
        self.PBZdelete.setText(_translate("MainWindow", "del"))
        self.PBZaktualisieren.setText(_translate("MainWindow", "ändern"))
        self.PBZutathinzu.setText(_translate("MainWindow", "hinzufügen"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Zutaten"))
        self.label_23.setText(_translate("MainWindow", "Cocktailname:"))
        self.PBenable.setText(_translate("MainWindow", "Enable all"))
        self.PBRnull.setText(_translate("MainWindow", "export + null"))
        self.CHBenabled.setText(_translate("MainWindow", "  Enabled"))
        self.PBclear.setText(_translate("MainWindow", "clear"))
        self.label_7.setText(_translate("MainWindow", "ml"))
        self.label_5.setText(_translate("MainWindow", "ml"))
        self.label_9.setText(_translate("MainWindow", "ml"))
        self.label_8.setText(_translate("MainWindow", "ml"))
        self.label_3.setText(_translate("MainWindow", "ml"))
        self.label_6.setText(_translate("MainWindow", "ml"))
        self.label_10.setText(_translate("MainWindow", "ml"))
        self.label_4.setText(_translate("MainWindow", "ml"))
        self.LWRezepte.setSortingEnabled(True)
        self.PBdelete.setText(_translate("MainWindow", "del"))
        self.PBRezeptaktualisieren.setText(_translate("MainWindow", "ändern"))
        self.PBRezepthinzu.setText(_translate("MainWindow", "hinzufügen"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Rezepte"))
        self.PBneu1.setText(_translate("MainWindow", "neu"))
        self.PBneu2.setText(_translate("MainWindow", "neu"))
        self.PBneu3.setText(_translate("MainWindow", "neu"))
        self.PBneu4.setText(_translate("MainWindow", "neu"))
        self.PBneu5.setText(_translate("MainWindow", "neu"))
        self.PBneu6.setText(_translate("MainWindow", "neu"))
        self.PBneu7.setText(_translate("MainWindow", "neu"))
        self.PBneu8.setText(_translate("MainWindow", "neu"))
        self.PBneu9.setText(_translate("MainWindow", "neu"))
        self.PBneu10.setText(_translate("MainWindow", "neu"))
        self.LBelegung1.setText(_translate("MainWindow", "LBelegung1"))
        self.LBelegung2.setText(_translate("MainWindow", "LBelegung2"))
        self.LBelegung3.setText(_translate("MainWindow", "LBelegung3"))
        self.LBelegung4.setText(_translate("MainWindow", "LBelegung4"))
        self.LBelegung5.setText(_translate("MainWindow", "LBelegung5"))
        self.LBelegung6.setText(_translate("MainWindow", "LBelegung6"))
        self.LBelegung7.setText(_translate("MainWindow", "LBelegung7"))
        self.LBelegung8.setText(_translate("MainWindow", "LBelegung8"))
        self.LBelegung9.setText(_translate("MainWindow", "LBelegung9"))
        self.LBelegung10.setText(_translate("MainWindow", "LBelegung10"))
        self.PBFlanwenden.setText(_translate("MainWindow", "neue Flaschen anwenden"))
        self.PBBelegung.setText(_translate("MainWindow", "ändern"))
        self.label_11.setText(_translate("MainWindow", "Flasche 1"))
        self.label_12.setText(_translate("MainWindow", "Flasche 2"))
        self.label_14.setText(_translate("MainWindow", "Flasche 3"))
        self.label_15.setText(_translate("MainWindow", "Flasche 4"))
        self.label_16.setText(_translate("MainWindow", "Flasche 5"))
        self.label_22.setText(_translate("MainWindow", "Flasche 6"))
        self.label_18.setText(_translate("MainWindow", "Flasche 7"))
        self.label_19.setText(_translate("MainWindow", "Flasche 8"))
        self.label_21.setText(_translate("MainWindow", "Flasche 9"))
        self.label_20.setText(_translate("MainWindow", "Flasche 10"))
        self.PBCleanMachine.setText(_translate("MainWindow", "CLEAN"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Belegung"))
        self.actionCocktailmaker.setText(_translate("MainWindow", "Cocktailmaker"))
        self.actionZutatenmanager.setText(_translate("MainWindow", "Zutatenmanager"))
        self.actionSlotbelegung.setText(_translate("MainWindow", "Slotbelegung"))
        self.actionRezeptverwalter.setText(_translate("MainWindow", "Rezeptverwalter"))

from clickablelineedit import ClickableLineEdit

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

