#!/bin/bash
# NOTE: ~/launcher.sh is a symlink pointing to this file.
# Do NOT edit this file directly if you want custom changes, as this file is tracked by git
# and updates to the project would overwrite your modifications.
# To make persistent local changes:
#   1. Unlink the symlink: rm ~/launcher.sh
#   2. Copy this file: cp ~/CocktailBerry/scripts/v1-launcher.sh ~/launcher.sh
#   3. Edit ~/launcher.sh as needed.

export QT_SCALE_FACTOR=1
cd "$HOME/CocktailBerry/" || echo "Did not find ~/CocktailBerry/"
bash scripts/dependency_installer.sh
uv run --no-dev --extra v1 --extra nfc runme.py
