#!/bin/bash
# NOTE: ~/launcher.sh is a symlink pointing to this file.
# Do NOT edit this file directly if you want custom changes, as this file is tracked by git
# and updates to the project would overwrite your modifications.
# To make persistent local changes:
#   1. Unlink the symlink: rm ~/launcher.sh
#   2. Copy this file: cp ~/CocktailBerry/scripts/v2-launcher.sh ~/launcher.sh
#   3. Edit ~/launcher.sh as needed.

cd "$HOME/CocktailBerry/" || echo "Did not find ~/CocktailBerry/"
bash scripts/dependency_installer.sh
uv run --extra nfc api.py
