# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Leaderboard(object):
    def setupUi(self, Leaderboard):
        Leaderboard.setObjectName("Leaderboard")
        Leaderboard.resize(800, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Leaderboard.sizePolicy().hasHeightForWidth())
        Leaderboard.setSizePolicy(sizePolicy)
        Leaderboard.setMinimumSize(QtCore.QSize(800, 480))
        Leaderboard.setMaximumSize(QtCore.QSize(2000, 1200))
        Leaderboard.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Leaderboard.setStyleSheet("QWidget\n"
                                  "{\n"
                                  "    color: rgb(0, 123, 255);    \n"
                                  "    background-color: rgb(14, 17, 23);\n"
                                  "\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton {\n"
                                  "    background-color: rgb(97, 97, 97);\n"
                                  "    color: rgb(255, 255, 255);\n"
                                  "    border-width: 1px;\n"
                                  "    border-color: rgb(97, 97, 97);\n"
                                  "    border-style: solid;\n"
                                  "    border-radius: 7;\n"
                                  "    padding: 3px;\n"
                                  "    padding-left: 5px;\n"
                                  "    padding-right: 5px;\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton:checked\n"
                                  "{\n"
                                  "    color: rgb(255, 255, 255);    \n"
                                  "    background-color: rgb(0, 123, 255);\n"
                                  "}\n"
                                  "\n"
                                  "QProgressBar\n"
                                  "{\n"
                                  "    background-color: rgb(166, 166, 166);\n"
                                  "    color: rgb(0, 0, 0);\n"
                                  "    border: 2px rgb(166, 166, 166);\n"
                                  "    border-radius: 5px;\n"
                                  "}\n"
                                  "\n"
                                  "QProgressBar::chunk {\n"
                                  "    border: 2px rgb(166, 166, 166);\n"
                                  "    border-top-left-radius: 5px;\n"
                                  "    border-bottom-left-radius: 5px;\n"
                                  "    border-top-right-radius: 5px;\n"
                                  "    border-bottom-right-radius: 5px;\n"
                                  "    background-color: rgb(0, 123, 255);\n"
                                  "   /* width: 40px;\n"
                                  "    margin: 0.5px;*/\n"
                                  "}\n"
                                  "\n"
                                  "#Labbruch {\n"
                                  "    color: rgb(239, 151, 0);\n"
                                  "}")
        self.centralwidget = QtWidgets.QWidget(Leaderboard)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.selectbtn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectbtn.sizePolicy().hasHeightForWidth())
        self.selectbtn.setSizePolicy(sizePolicy)
        self.selectbtn.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.selectbtn.setFont(font)
        self.selectbtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.selectbtn.setObjectName("selectbtn")
        self.horizontalLayout.addWidget(self.selectbtn)
        Leaderboard.setCentralWidget(self.centralwidget)

        self.retranslateUi(Leaderboard)
        QtCore.QMetaObject.connectSlotsByName(Leaderboard)

    def retranslateUi(self, Leaderboard):
        _translate = QtCore.QCoreApplication.translate
        Leaderboard.setWindowTitle(_translate("Leaderboard", "Leaderboard"))
        self.selectbtn.setText(_translate("Leaderboard", "C\n"
                                          "h\n"
                                          "a\n"
                                          "n\n"
                                          "g\n"
                                          "e\n"
                                          " \n"
                                          "D\n"
                                          "i\n"
                                          "s\n"
                                          "p\n"
                                          "l\n"
                                          "a\n"
                                          "y"))
