__version__ = "1.10.0"
PROJECT_NAME = "CocktailBerry"
MAX_SUPPORTED_BOTTLES = 16
SUPPORTED_LANGUAGES = ["en", "de"]
SUPPORTED_BOARDS = ["RPI"]
SUPPORTED_THEMES = ["default", "bavaria"]
NEEDED_PYTHON_VERSION = (3, 7)
