---
  name: Release Drafter
  run-name: ✏️ Update release draft
  
  # yamllint disable-line rule:truthy
  on:
    push:
      branches:
        - master
    workflow_dispatch:
  
  permissions:
    contents: write
    pull-requests: write

  jobs:
    update_release_draft:
      name: ✏️ Draft release
      runs-on: ubuntu-latest
      steps:
        - name: 🚀 Run Release Drafter
          uses: release-drafter/release-drafter@72967cdc98ddd3160f1fc3dff619de365e137dd0 # v7.9.0
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}